woowacourse/java-mvc

app/build.gradle, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/TestController.java, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/controller/scanner/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/scanner/RequestMappingScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/test/java/nextstep/mvc/controller/scanner/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/controller/scanner/RequestMappingScannerTest.java, mvc/src/test/java/nextstep/mvc/controller/scanner/test_classes/Test1.java, mvc/src/test/java/nextstep/mvc/controller/scanner/test_classes/Test2.java
안녕하세요 제리!
TestController에서 index.html로 redirect 되도록 해봤습니다!
잘 부탁드립니다!
=> [MVC 구현하기 - 1단계] 손너잘(손민성) 미션 제출합니다. 

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/JwpApplication.java, app/src/main/java/com/techcourse/controller/TestController.java, app/src/main/java/com/techcourse/support/web/filter/CharacterEncodingFilter.java, app/src/main/java/com/techcourse/support/web/filter/ResourceFilter.java, app/webapp/get-test.jsp, app/webapp/post-test.jsp, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/adaptor/ControllerAdaptor.java, mvc/src/main/java/nextstep/mvc/adaptor/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/adaptor/HandlerExecutionAdaptor.java, mvc/src/main/java/nextstep/mvc/controller/asis/Controller.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/scanner/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/scanner/RequestMappingScanner.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/main/java/nextstep/web/WebApplicationInitializer.java, mvc/src/main/java/nextstep/web/annotation/Controller.java, mvc/src/main/java/nextstep/web/annotation/PathVariable.java, mvc/src/main/java/nextstep/web/annotation/RequestMapping.java, mvc/src/main/java/nextstep/web/annotation/RequestParam.java
안녕하세요 알리입니다!
이번 미션은 코드 작성 시간보다 이해 자체가 너무 어려워 고민했던 시간이 많았던 것 같네요ㅜㅜ
감사합니다!
=>  [MVC 구현하기 - 1단계] 알리(허진호) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerAdaptor.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LogoutController.java, app/src/main/java/com/techcourse/controller/TestController.java, learning/build.gradle, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/asis/Controller.java, mvc/src/main/java/nextstep/mvc/controller/asis/ForwardController.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdaptor.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/view/JsonView.java, mvc/src/main/java/nextstep/mvc/view/JsonViewResolver.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/JspViewResolver.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/main/java/nextstep/mvc/view/View.java, mvc/src/main/java/nextstep/mvc/view/ViewResolver.java, mvc/src/main/java/nextstep/web/annotation/RequestMapping.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java
안녕하세요 코다 우기 입니다! 
디스패처 서블릿 코드가 변경되지 않게 하면서, 다양한 종류의 핸들러(컨트롤러)가 동작하고 다양한 종류의 뷰가 응답될 수 있도록 핸들러 매핑, 핸들러 어댑터, 뷰 리졸버 등을 구현했습니다! 디스패처 서블릿 코드를 참고 하면서 진행했어요 
피드백 주시면 많이 배우면서 부족한 부분 적극적으로 개선 해보겠습니다 😃
리뷰감사합니다 ㅎㅎ
=> [MVC 구현하기 - 1단계] 우기(박병욱) 미션 제출합니다. 

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/TestController.java, app/webapp/get-test.jsp, app/webapp/post-test.jsp, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestController.java
안녕하세요 피케이! 바다입니다 🌊
MVC 미션 1단계까지 구현해보았습니다.
이후 단계들을 진행하며 요구사항에 맞춰 리팩터링하고 싶어서 아직 크게 리팩터링은 하지 않은 상태입니다 ~
리뷰에 참고해주세요!
리뷰 미리 감사드립니다 ㅎㅎ 🙏
=> [MVC 구현하기 - 1단계] 바다(조아라) 미션 제출합니다. 

README.md, app/build.gradle, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/domain/User.java, app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java, app/webapp/login.jsp, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/handleradapter/AnnotaionHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handleradapter/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handleradapter/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/handleradapter/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handlermapping/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/handlermapping/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/handlermapping/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/servlet/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java
안녕하세요! 마크!
항상 축구 이야기로만 간간히 뵙다가 코드 이야기로 뵙게 되었습니다! 잘 부탁드릴게요.
이번 미션은 Servlet과 스프링 구조를 돌아보는 미션인 것 같아서 Spring 구조 그림을 옆에 가져다두고 진행하게 되었습니다.
리플랙션 및 어노테이션을 이정도로 깊게 사용해보는 것이 처음이라 어려웠긴 했지만, 실제 구조를 볼 수 있어서 좋았습니다.
이번 미션 잘 부탁드릴게요!
=> [MVC 구현하기 - 1단계] 와이비(허영범) 미션 제출합니다. 

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/TestController.java, app/webapp/get-test.jsp, app/webapp/post-test.jsp, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java
안녕하세요 욘!!! 피카입니다!!!!!!!!!!!!
이번에 코드가 굉장히 잘되어있어서 따라가기만 한 것 같네요!!
부족한 코드이지만 잘 봐주시면 감사하겠습니다!! :)
=> [MVC 구현하기 - 1단계] 피카(윤지우) 미션 제출합니다. 

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerAdapter.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/annotaion/IndexPageController.java, app/src/main/java/com/techcourse/controller/annotaion/LoginController.java, app/src/main/java/com/techcourse/controller/annotaion/LogoutController.java, app/src/main/java/com/techcourse/controller/annotaion/RegisterController.java, app/src/main/java/com/techcourse/controller/manual/LoginController.java, app/src/main/java/com/techcourse/controller/manual/LoginViewController.java, app/src/main/java/com/techcourse/controller/manual/LogoutController.java, app/src/main/java/com/techcourse/controller/manual/RegisterController.java, app/src/main/java/com/techcourse/controller/manual/RegisterViewController.java, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/exception/NotExistException.java, mvc/src/main/java/nextstep/mvc/view/JspView.java
안녕하세요 로키~~
잘지내고 계신가요ㅎㅎ
이번 미션도 역시 어렵군요.. 그래도 스프링의 동작 원리를 조금이나마 알 수 있어서 재밌었습니다
흐름은 이렇습니다
1. 요청이 들어오면 DispatcherServlet에서 등록된 HandlerMapping을 찾아서 해당 HandlerMapping의 getHandler 반환값을 줌. (실제 스프링에서는 HandlerMapping의 우선 순위가 있던데 일단 그런거 없이 findFirst로 해주었습니당)
2. AnnotationHandlerMapping이라면 getHandler 반환값이 HandlerExecution이고 ManualHandlerMapping이라면 Controller 이기에 이를 이용해 각각에 맞는 HandlerAdapter를 조회함.
3. HandlerAdapter의 handle을 통해 ModelAndView를 반환함
4. ModelAndView내 View의 render를 통해 클라이언트에게 응답을 줌.
현재 생각하는건 AnnotaionHandlerMapping의 initialize내 로직이 뭔가 실제 스프링에서 ComponentScan이 하는 동작 같은데 따로 빼는게 맞나 생각중입니다..
아무래도 흐름에 집중하다 보니 자잘한 부분은 부족한게 많다고 생각하는데 따끔하게 피드백 주세요~~!! 감사합니다!!!
=> [MVC 구현하기 - 1단계] 오즈(오주형) 미션 제출합니다. 

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerAdapter.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/annotationcontroller/AnnotationLoginController.java, app/src/main/java/com/techcourse/controller/interfacecontroller/LoginController.java, app/src/main/java/com/techcourse/controller/interfacecontroller/LoginViewController.java, app/src/main/java/com/techcourse/controller/interfacecontroller/LogoutController.java, app/src/main/java/com/techcourse/controller/interfacecontroller/RegisterController.java, app/src/main/java/com/techcourse/controller/interfacecontroller/RegisterViewController.java, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/build.gradle, mvc/src/main/java/nextstep/mvc/AnnotationRequestHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/ComponentScanner.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java
에어 안녕하세요 ~~!!! 코다입니다 :)
모듈간 의존하고 있는 구조와 스프링 MVC의  DispatcherServlet 에서 HandlerAdapter, HandlerMapping, ModelAndView를 어떻게 처리하는지 공부하느라 시간이 좀 걸린 것 같아요 ~~!!! 
두개의 controllerMapping(기존의 controller interface 형식, annotation 형식)이 공존하는지 확인하기 위해서 
login에 관련된 컨트롤러 메서드를 AnnotationLoginController에 어노테이션 형식으로 옮기고 기존 Controller를 ManualHandlerMapping에서 제거했습니다. 🙌
이번에 하면서 ManualHandlerMapping은 app 모듈에 있는데 AnnotationHandlerMapping은 mvc 프레임 영역에 가깝다고 생각이 들어서 mvc 모듈에 포함했어요 !! 살짝 어색한 것도 같긴 한데 ,, 에어는 어떻게 생각하나요 ?? 
나름 보면서 비슷하게 구현하려고 했는데 `AnnotationHandlerMapping` 의 `initialize()`부분의 코드가 지저분한거 같네요 ㅠㅠㅠ 
테스트도 작성해보려고 했으나 프레임워크 부분에 대한 테스트도 어떻게 진행해야할지 잘 모르겠네요 !! 
엄청난 리뷰 기대할게요 ...^^ 
리뷰 잘 부탁드립니다 ~~!! 😊🎉
=> [MVC 구현하기 - 1단계] 코다(김윤정) 미션 제출합니다. 

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdaptor.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerHandlerAdaptor.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/exception/NotFoundHandlerAdapterException.java, mvc/src/main/java/nextstep/mvc/exception/NotFoundHandlerException.java, mvc/src/main/java/nextstep/mvc/view/JspView.java
조엘 오랜만이네요 👋🏻
루터에 안나간지 한참 됐네요... 그만큼 조엘 안본지도 엄~~청 오래된 것 같습니다 🥲
이렇게 리뷰어로 만나뵈니 반갑네요 😃 
주변 크루들을 보니 레벨4는 참 바쁜시기인것 같아요~ 👀
저도 일정에 치이다보니 시간 관리가 잘 안돼서 '사자' 마냥 밀림의 왕이 되어가고 있어요 🥲🤣
조엘은 어떠신가요?  
미션 얘기로 돌아가서 
이번 미션 진짜 쉽지 않네요.... 😨  레벨 4... 확실히 어렵다고 느껴집니다. 
테스트 통과하게 만드는 것 까지는 어찌저찌 했는데... (AnnotationHandlerMappingTest는 빼구... 🥲, HandlerExecution을 어떻게 변경해야할지 감을 못잡아서 한참 걸렸네요 )
잘 구현했는지 확인하고 싶어서 HandlerMapping 등록해놓고 돌려봤는데, 이게 어디서부터 문제인지를 몰라서 한참 애먹었네요 🥲
결국 다른 크루들의 코드를 조금 참고하면서 해결했네요 😃 
기존 Controller 들을 모두 애너테이션 기반으로 변경하고 싶었지만... 
미션 요구사항이 `컨트롤러 인터페이스 기반 MVC 프레임워크와 어노테이션 기반 MVC 프레임워크가 공존하도록 만들자.` 인 만큼! 
Controller 중에서 `[GET]. [POST] /register` 기능의 경우 (`RegisterController`)만 애너테이션 기반으로 변경하였습니다 😃
피드백 달게 받겠습니다 🙏 맘 편하게 던져주세요!! 🕺
=> [MVC 구현하기 - 1단계] 로키(김경록) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/support/web/filter/CharacterEncodingFilter.java, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/build.gradle, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/adapter/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/adapter/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/adapter/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/scanner/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/exception/NotFoundException.java, mvc/src/main/java/nextstep/mvc/mapping/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/mapping/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/test/java/nextstep/mvc/controller/scanner/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/web/support/RequestMethodTest.java
이번 미션에서는 ComponentScan와 DispatcherServlet 리팩토링을 중점을 두고 구현했어요!
기존 SpringMVC의 DispatcherServlet을 많이 참고하여 구현했습니다!
이번주에 테코톡 준비로 인해 미션 제출 시간이 조금 많이 늦어졌네요ㅠㅠ
테스트는 차근차근 채워나갈게요!ㅎㅎ (테스트 작성하고내면 너무 오래 걸릴 것 같아 일단 제출합니다!)
피드백 남겨주시면 최대한 빨리 리팩토링해볼게요ㅎㅎ 잘부탁드려요~~~
=> [MVC 구현하기 - 1단계] 마크(김병화) 미션 제출합니다.

app/src/main/java/com/techcourse/JwpApplication.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/TestController.java, app/src/main/java/com/techcourse/controller/UserSession.java, app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ParameterResolver.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ParameterResolverExecutor.java, mvc/src/main/java/nextstep/mvc/handler/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handler/HandlerAdapters.java, mvc/src/main/java/nextstep/mvc/handler/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/handler/HandlerMappings.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/controller/asis/ControllerHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerExecutionAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ParameterResolverExecutorTest.java
안녕하세요 현구막~~
1단계 때 다양한 질문과 꼼꼼한 리뷰를 해준 현구막 덕에 즐거웠습니다!
1단계 때 당부한 꼭꼭꼭 대답은 
https://github.com/woowacourse/jwp-dashboard-mvc/pull/8#discussion_r706569127
https://github.com/woowacourse/jwp-dashboard-mvc/pull/8#discussion_r706567735
두 개의 코멘트에 달아놓았습니다. 
2단계로 미룬 반영을 마치고, 추가적으로 코기의 코드를 리뷰하다 재밌어 보였던 동적 파라미터 바인딩을 구현해보았습니다!
이름은.. ParameterResolver라고 지었습니다. 왜 ArgumentResolver가 아니냐구요?
제 마음입니다.
그리고 스트릿 우먼 파이트 보세요. 너무 재밌어.. 재미의 덫에 빠져버렸습니다.
리뷰 잘 부탁드립니다!
=> [MVC 구현하기 - 2단계] 웨지(성시형) 미션 제출합니다. 

.gitignore, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/JwpApplication.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/UserSession.java, app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java, app/src/main/java/com/techcourse/support/web/filter/CharacterEncodingFilter.java, app/src/main/java/com/techcourse/support/web/filter/ResourceFilter.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerMappings.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/handler/adaptor/AnnotationHandlerAdaptor.java, mvc/src/main/java/nextstep/mvc/handler/adaptor/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handler/adaptor/HandlerAdapters.java, mvc/src/main/java/nextstep/mvc/handler/adaptor/ManualHandlerAdaptor.java, mvc/src/main/java/nextstep/mvc/handler/mapping/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/handler/mapping/HandlerMappings.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/RedirectView.java, mvc/src/main/java/nextstep/mvc/view/ViewResolver.java, mvc/src/test/java/nextstep/mvc/HandlerMappingsTest.java, mvc/src/test/java/nextstep/mvc/view/ViewResolverTest.java
=> [MVC 구현하기 - 2단계] 손너잘(손민성) 미션 제출합니다. 

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/UserController.java, app/webapp/index.html, app/webapp/index.jsp, app/webapp/login.jsp, app/webapp/register.jsp, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JsonView.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/View.java
영이 하이염~~
많이 늦었네요 ㅠ
일단 돌아가게만 구현했습니다,,
제가 늦은만큼 리뷰도 천천히 주셔도 됩니다,,
=> [MVC 구현하기 - 1단계] 라이언(권영훈) 미션 제출합니다. 

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/JwpApplication.java, app/src/main/java/com/techcourse/adapter/AnnotationHandlerAdapter.java, app/src/main/java/com/techcourse/adapter/ManualHandlerAdapter.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/TestController.java, app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java, app/src/main/java/com/techcourse/support/web/filter/ResourceFilter.java, app/webapp/get-test.jsp, app/webapp/post-test.jsp, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/build.gradle, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/adapter/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/adapter/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/adapter/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/samples/TestController.java
안녕하세요 파피 포모입니다!
저는 이번 미션에서 주어진 요구사항을 다 구현하는 것을 목표로 진행하였습니다!
미션의 단계를 순차적으로 진행하면서 코드를 리팩토링해보았습니다 :)
아직 완벽하지 않은 코드이지만, 파피의 피드백을 받으면서 더 좋은 코드로 고쳐보도록 하겠습니다.
코드 리뷰에 시간 내주셔서 감사합니다. ☺️
=> [MVC 구현하기 - 1단계] 포모(박은소리) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/TestController.java, app/webapp/get-test.jsp, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java
안녕하세요 찰리!!!!!!!!!!! 오랜만이네요 그쵸 ㅎㅎ DDD 장인에게 리뷰를 받게 되어 영광입니다!
먼저 리뷰 요청이 늦어서 죄송합니다 몸이 안좋아서 정신이 없네요..😢 
부족한 점이 많을 텐데 가감없는 피드백 부탁드립니다!
시간 내어주셔서 감사합니다 🙏 🙏
=> [MVC 구현하기 - 1단계] 파피(김태완) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/TestController.java, app/webapp/get-test.jsp, app/webapp/post-test.jsp, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/JunitOutput.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/AdapterNotFoundException.java, mvc/src/main/java/nextstep/mvc/AnnotationBasedAdapter.java, mvc/src/main/java/nextstep/mvc/ControllerBasedAdapter.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/HandlerAdapters.java, mvc/src/main/java/nextstep/mvc/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/HandlerMappings.java, mvc/src/main/java/nextstep/mvc/HandlerNotFoundException.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerCreationException.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/view/JspView.java
나름 많이 배워보고 싶어서 천천히 학습하느라 시간이 좀 걸렸네요!
코기가 리뷰어라 더 설레는 마음으로 만들어봤어요.
스텝 1 요구사항에 맞는 기능만 만들어져 있습니다. 아직 리팩토링 할 부분은 있을 것 같네요.
스텝2나 피드백 부분은 아직 일부러 안 본 상태라 거기 적힌 힌트와는 조금 다르게 만들어져 있을 수도 있습니다!
이번 미션을 통해서 프레임워크에 대해 생각해보고 이것 저것 많이 시도해보는 시간을 가져보고 싶어요.
그러니 시간에 관계 없이 리뷰 해주시면 감사하겠습니다!
그리고 그 어떤 리뷰나 의견, 아니면 질문 모두 받고 싶습니다. 페어하듯 리뷰해주세요 😁
=> [MVC 구현하기 - 1단계] 피케이(박유진) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/TestController.java, app/webapp/get-test.jsp, app/webapp/post-test.jsp, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java
수리 안녕하세요!!! 제출이 많이 늦었네요..! 
1단계 요구사항 3개를 우선 구현해보자라는 생각으로 해봤습니다.
피드백 수업 후에 리팩토링 진행하며 추가 수정 및 구현 해볼게요.
리뷰는 편하게 어떤 부분이든 주시면 감사하겠습니다~
=> [MVC 구현하기 - 1단계] 욘(김영빈) 미션 제출합니다. 

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/TestController.java, app/webapp/get-test.jsp, app/webapp/post-test.jsp, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ExecutionHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/utils/AnnotationScanner.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java
리뷰어 파즈 정말 반가워요~
어노테이션 학습을 하고, 미션을 진행해보았습니다.
코드 리뷰 부탁 드릴게요!!
감사합니다 :)
=> MVC 구현하기 - 1단계] 수리(이다원) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/AnnotationLoginController.java, app/src/main/java/com/techcourse/controller/AnnotationLogoutController.java, app/src/main/java/com/techcourse/controller/AnnotationRegisterController.java, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java
안녕하세요 춘식! 정말 정말 늦어서 죄송합니다...  
테스트코드는 못짰어요 ㅜㅜ 2,3단계 하면서 같이 해보겠습니다! 그리고 css,js 부분이 정상적으로 동작을 안해요!  
디버그 찍어보니깐 ``ResourceFilter`` 에 아예 들어가지를 않더라구요! 필터 부분을 다른 곳에서 따로 추가를 해줘야되나? 싶은데 혹시 아시나요 !?  
어댑터는 적용을 안했어요! 현재 어노테이션 기반 핸들러 매핑만 등록해놨습니다! 2단계 내용이어서 2,3 같이하면서 추가할게요! 늦어서 죄송합니다 ㅜㅜ 리뷰 감사합니다!
=> [MVC 구현하기 - 1단계] 파즈(강승윤) 미션 제출합니다. 

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/DummyController.java, app/webapp/test.jsp, learning/src/test/java/reflection/Junit3TestRunner.java, learning/src/test/java/reflection/Junit4TestRunner.java, learning/src/test/java/reflection/ReflectionTest.java, learning/src/test/java/reflection/ReflectionsTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/web/annotation/RequestMapping.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java
안녕하세요 조이! 조금 늦었지만 미션 제출합니다.
이번 미션은 요청과 응답의 흐름을 따라가기만 해도 벅차더라구요 
코드의 어떤 부분을 만들어야 하고 어떤 부분이 부족한지, 어떤 책임을 가지고 있는 객체인지 등, 전체적인 흐름을 파악하기가 어려웠어요
그래서 `adapter` 는 아직 추가로 도입하지 않은 상태입니다. step 2 리펙토링 과정에서 처리하려고 해요
각 클래스가 책임을 명확히 가지고 있는지를 중점으로 봐주시면 감사하겠습니다!
=> [MVC 구현하기 - 1단계] 마갸(정찬영) 미션 제출합니다. 

README.md, app/src/main/java/com/techcourse/controller/annotationcontroller/AnnotationForwardController.java, app/src/main/java/com/techcourse/controller/annotationcontroller/AnnotationRegisterController.java, app/src/main/java/com/techcourse/controller/annotationcontroller/UserController.java, app/src/main/java/com/techcourse/domain/User.java, mvc/build.gradle, mvc/src/main/java/nextstep/mvc/ComponentScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/view/JsonView.java, mvc/src/test/java/nextstep/mvc/ComponentScannerTest.java, mvc/src/test/java/nextstep/mvc/view/JsonViewTest.java, mvc/src/test/java/samples/TestUser.java
안녕하세요 에어 ~~!! 
2단계 리팩토링 요구사항을 1단계 구현하면서 어느 정도 충족했다고 생각해서 한꺼번에 PR 보냅니다 !! 
View를 실제로 처리하는 방식에서 대해서 나름 공부하면서 구현했는데 맞게 구현했는지 모르겠네요 ,,ㅎㅎ 
제공된 UserController도 뒤에 queryString을 인위적으로 덧붙여서 요청을 보냈을 때 json 값을 출력하더라구요 !! 
이외에 기존 controller 인터페이스 방식을 모두 삭제한 뒤에 잘 돌아가는 것도 확인했습니다 ㅎㅎㅎ 
피드백 감사합니다 !! 👍😊
=> [MVC 구현하기 - 2,3단계] 코다(김윤정) 미션 제출합니다.

app/build.gradle, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/annotationcontroller/AuthController.java, app/src/main/java/com/techcourse/controller/annotationcontroller/ForwardController.java, app/src/main/java/com/techcourse/controller/annotationcontroller/MemberController.java, app/src/main/java/com/techcourse/controller/annotationcontroller/UserController.java, app/src/main/java/com/techcourse/controller/lagacy/LoginController.java, app/src/main/java/com/techcourse/controller/lagacy/LoginViewController.java, app/src/main/java/com/techcourse/controller/lagacy/LogoutController.java, app/src/main/java/com/techcourse/controller/lagacy/RegisterController.java, app/src/main/java/com/techcourse/controller/lagacy/RegisterViewController.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/asis/InterfaceBasedControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/exception/UnsupportedViewFileExtensionException.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerAdapters.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionHandlerAdaptor.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerMappings.java, mvc/src/main/java/nextstep/mvc/controller/tobe/InterfaceBasedControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/view/JsonView.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/web/support/Header.java, mvc/src/main/java/nextstep/web/support/MediaType.java, mvc/src/test/java/nextstep/mvc/controller/asis/InterfaceBasedControllerHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerExecutionHandlerAdaptorTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/InterfaceBasedControllerHandlerAdapterTest.java
안녕하세요 크로플! 김김입니다 :)
2단계를 진행하며 요구사항에 따라 구현한 부분은 다음과 같습니다.
- `ControllerScanner`의 구현
- `HandlerAdapter`의 구현 (1단계에서 피드백주신, `DispatcherServlet`의 분기가 사라졌습니다👍)
이미 1단계에서 진행한 2단계의 요구사항은 다음과 같네요!
- `HandlerExecution`의 생성
잘 부탁드립니다🙇‍♂️ :)
P. S. 2021/09/16
3단계를 진행하였습니다.
- `JsonView`의 구현
- `ManualHandlerMapping`을 전혀 사용하지 않도록 `app` 모듈 구현
감사합니다 :)!
=> [MVC 구현하기 - 2, 3단계] 김김(김기문) 미션 제출합니다. 

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerAdapter.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/main/java/nextstep/web/exception/NotFoundException.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java, mvc/src/test/java/nextstep/mvc/view/ModelAndViewTest.java
안녕하세요 배카라! 주말 잘 보내고 계신가요?
오늘은 날씨가 더운데 다음주부터 쌀쌀해 질 것 같더라구요. 🥲 중요한 시기에 감기 안걸리도록 조심하셔요!
처음엔 어떻게 구현해야할지 막막했는데 구현하다보니 핸들러매핑, 핸들러어댑터가 어떤 동작을 하는지 이해하게 되면서 재밌어지더라구요😃
가장 어려웠던 점은 테스트코드를 작성하는 거였어요. mock을 활용하여 테스트할 수 있는 부분을 테스트했습니다!
이번엔 로그도 신경을 써봤는데요. 실제 프레임워크는 debug와 trace를 활용하더라구요. 
미션이어서 편하게 보기위해 info레벨로 로깅을 했는데 추가적으로 로그를 작성하면 좋을 부분도 같이 고민해보면 좋을 것 같아요!
리뷰남겨주시면 열심히 고민해볼게요!!
배카라도 미션 화이팅입니다!!!☺️
---
어노테이션 기반으로도 동작하는 걸 확인하기 위해 로그인 페이지 요청은 어노테이션 기반으로 만들었어요.
=> [MVC 구현하기 - 1단계] 호호(유현호) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerAdapter.java, app/src/test/java/com/techcourse/ManualHandlerAdapterTest.java, app/src/test/java/com/techcourse/ManualHandlerMappingTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java, mvc/src/test/java/nextstep/mvc/view/ModelAndViewTest.java
안녕하세요 기론! MVC 구현하기 미션으로 만나서 반갑습니다 😄
처음에는 요청을 어떻게 핸들링할지 고민하느라 막막하더라고요 😢 특히 HandlerAdapter를 사용하는 방식에 대해서 이해가 잘 안갔어서 고생을 좀 했습니다 ㅠㅠ 그래도 어찌 어찌 동작은 잘 되게 만들었는데, 혹시 제가 놓친 부분이 있을지도 모르겠어요 👀 
특히 테스트 코드를 좀 더 작성해보고 싶은데, 우선 있는 테스트들은 mock 처리를 통해 잘 진행한 것 같지만 DispatcherServlet 관련 테스트가 없어서, 어떤 방식으로 테스트할 수 있을지가 고민입니다. 좋은 의견 있다면 한 수 가르쳐주세요 😄 
좋은 리뷰 부탁드리고 기론도 미션 화이팅입니다 🔥
=> [MVC 구현하기 - 1단계] 오찌(오지훈) 미션 제출합니다.

README.md, app/build.gradle, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerAdapter.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/LogoutController.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, app/src/main/java/com/techcourse/controller/UserSession.java, app/src/test/java/com/techcourse/ManualHandlerAdapterTest.java, app/src/test/java/com/techcourse/controller/ManualHandlerMappingTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/asis/ForwardController.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/main/java/nextstep/web/annotation/PathVariable.java, mvc/src/main/java/nextstep/web/annotation/RequestMapping.java, mvc/src/main/java/nextstep/web/annotation/RequestParam.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java, settings.gradle, test/build.gradle
썸오 ~~ 안녕하세요 수달 입니다. ㅎㅎㅎ
리뷰어로 만나게 되어서 정말 정말 기대 되네요! 
이번 미션 하면서 Spring 동작 원리를 파악하는 점이 재밌었어요!
학습한 내용도 공유하고,  즐겁게 대화 나누고 싶어요.  잘부탁드립니다 👍🏻
=> [MVC 구현하기 - 1단계] 수달(허수진) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/webapp/WEB-INF/classes/logback.xml, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerMethod.java, mvc/src/main/java/nextstep/mvc/view/DefaultView.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ViewFactory.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerExecutionTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerMethodTest.java, mvc/src/test/java/nextstep/mvc/view/ViewFactoryTest.java, mvc/src/test/java/samples/TestReflections.java
안녕하세요 에덴!!
1단계 요구사항만 간단하게 완료하여 미션 제출합니다! 
리뷰 잘 부탁드립니다 !!
=> [MVC 구현하기 - 1단계] 후니(최재훈) 미션 제출합니다.

mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/samples/TestController.java, mvc/src/test/java/samples/TestForwardManualController.java, mvc/src/test/java/samples/TestManualHandlerMapping.java, mvc/src/test/java/samples/TestRedirectManualController.java
안녕하세요 써머~
1단계까지 작업했습니다 ㅎㅎ
DispatcherServlet에서 getModelAndView 메서드 내부에 분기문을 이용해 ModelAndView를 가져오도록 했습니다.
이 부분은 2단계때 HandlerAdapter를 적용하면서 분기문을 없앨 수 있을 것 같아요 ㅎㅎ
=> [MVC 구현하기 - 1단계] 베루스(정진혁) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/LoginControllerV2.java, app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/adapter/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/adapter/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/adapter/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/asis/ForwardController.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/view/JsonView.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/View.java, mvc/src/main/java/nextstep/web/NextstepServletContainerInitializer.java, mvc/src/main/java/nextstep/web/annotation/PathVariable.java, mvc/src/main/java/nextstep/web/annotation/RequestMapping.java, mvc/src/main/java/nextstep/web/annotation/RequestParam.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java, mvc/src/test/java/nextstep/mvc/adapter/AnnotationHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java
안녕하세요 티키! 
리뷰어에서 리뷰이로 인사를 드립네요! ㅎㅎ 이번 미션 쉽지가 않네요.
AnnotationHandlerMapping은 구현을 했고, AnnotationHandler가 잘 동작하기 위해서 HandlerAdapter를 썼네요. 2단계 때하는 것인줄 모르고 기존 코드에 있길래 사용을 했습니다. 
리뷰 잘 부탁드려요!
=> [MVC 구현하기 - 1단계] 토르(손인준) 미션 제출합니다. 

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/asis/HandlerControllerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionAdapter.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/controller/asis/HandlerControllerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerExecutionAdapterTest.java
안녕하세요 토르!
이번 미션은 테스트 코드 짜기가 참 쉽지가 않네요 ㅠㅠ
그래서 테스트 코드가 빈약합니다..
조금씩 보완하도록 하겠습니다!
리뷰 잘 부탁드리겠습니다!
=> [MVC 구현하기 - 1단계] 승팡(김승래) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java
안녕하세요, 크리스~👋 
미션에선 만난 적 없는 것 같은데 반갑습니다 ㅎㅎ
일단 요구사항이 충족되게 구현은 다 끝냈는데요, 
지금 구현 상황에서 적절한 테스트가 떠오르지 않아 고민입니다 
원래 `DispatcherServelet`이 `ManualHandlerMapping, AnnotationHandlerMapping`을 잘 처리하는지 테스트 하려고 했는데, 
`ManualHandlerMapping`의 경우 서비스 영역이라 `DispatcherServlet`쪽 테스트에서 사용할 수가 없더라고요  
그 외에는 테스트하기 적합한 단위로 보이는 곳이 없어서 💦 크리스는 어떻게 테스트 하셨는지 경험을 듣고싶습니다  
그리고 커밋 수도 그렇고 결과물이 좀 썰렁해서 제가 요구사항에 맞게 구현한건지 의구심이 드네요... 
이번 미션 기간 동안 잘부탁드려요!
=> [MVC 구현하기 - 1단계] 써머(최혜원) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/exception/RequestMethodException.java, mvc/src/main/java/nextstep/mvc/exception/ServletException.java, mvc/src/main/java/nextstep/mvc/handlerAdapter/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handlerAdapter/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handlerAdapter/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handlerMapping/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/handlerMapping/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/handlerAdapter/AnnotationHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/handlerAdapter/ManualHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java, mvc/src/test/java/nextstep/web/support/RequestMethodTest.java
안녕하세요 제로! 
미션 진행하면서 개인적으로 많이 헤멨어서 적절한 구조가 맞는지 아직도 조금 헷갈리네요 ㅠㅠ 조금 더 구조에 대해서 고민하면서 고쳐보도록 하겠습니다 👍
테스트의 경우에는 조금 더 다양하게 짜고 싶었으나 방식을 제대로 찾지 못한 것 같아서 간단하게만 짰습니다. 
이해 안되는 부분이 있으면 편하게 DM 주세요! 감사합니다~
=> [MVC 구현하기 - 1단계] 루나(남민정) 미션 제출합니다.

app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/ResourceRequestController.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java
안녕하세요 조조그린!! 이렇게 만나 뵙게 돼서 영광입니다!!
잘 부탁드립니다!!
이번 미션을 하면서 spring 에서 제공하는 View의 역할에 대해서 생각해볼 수 있는 시간이였어요.
SSR을 제대로 해본적이 없어서 ModelAndView와 View의 역할이 아직 어색하게 느껴지네요.
앞으로 미션을 진행하면서 더 공부해보겠습니다!!
=> [MVC 구현하기 - 1단계] 칙촉(안영윤) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualMappingHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/RequestMappingHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java
=> [MVC 구현하기 - 1단계] 주디(윤주리) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/TestController.java, app/src/main/webapp/WEB-INF/classes/logback.xml, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java
안녕하세요 이프~👋🏻
이렇게 미션으로 다시 만나니 반갑네요ㅎㅎ
요구사항이 충족되는 선에서 최소한의 코드를 짜보려고 했습니다.
HandlerAdapter를 도입하지 않았고 우선 내부에서 처리하고 있는데 2단계 때 진행하려고 합니다.
추가로 Test 관련해서 코드를 짜보려고 했는데, 어디를 테스트 해야할지 감이 안와서 우선 작성하지 않았습니다.
테스트를 만든다면 Annotation 기반 핸들러와 수동으로 주입한 컨트롤러를 올바르게 가져오는지 테스트하고 싶은데 애매해서 우선 보류했습니다.
테스트 코드가 없다보니 제대로 구현한건지 스스로 의심이 조금 드는데, 잘못된 점이 있다며  편하게 리뷰 남겨주세요!!
=> [MVC 구현하기 - 1단계] 아서(김현태) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/TestController.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/exception/NotFoundHandlerException.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/DispatcherServletTest.java
안녕하세요 토닉😆 리뷰를 받게되어 영광입니다. 1단계를 완료했어요. 
생각보다 코드량은 많지 않은데 생소한 부분이 있어 시간이 걸렸네요.
제안사항은 마음껏 의견주시면 좋겠습니다!
=> [MVC 구현하기 - 1단계] 레오(남궁현) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/exception/NoConstructorException.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/exception/NotFoundViewException.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java, mvc/src/test/java/nextstep/web/support/RequestMethodTest.java
안녕하세요 릭! 이스트입니다~~ 😄
~~2단계 요구사항을 침범하지 않으려고 하다보니 DispatcherServlet에서 render하는 부분에 `Collections.EmptyMap()`을 넣게 되어 조금 어색하네요...!~~
AnnotationHandlerMapping 을 테스트코드에서만 작동하도록 구현했었네요...! 어플리케이션에서도 작동하도록 코드를 변경했습니다!
이번 미션 잘 부탁드립니다~~
=> [MVC 구현하기 - 1단계] 이스트(신동훈) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java
안녕하세요 호호~😶‍🌫️
미션은 HandlerAdapter 없이 if분으로 나눠서 처리했어요. 2단계 진행하면서 분리하겠습니다!
고민 사항은 DispatcherServlet 테스트를 어떻게 해야할 지 모르겠어요. 이부분은 조금 더 고민해보고 추가해보겠습니다.
감사합니다😁
=> [MVC 구현하기 - 1단계] 슬로(이한울) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, docs/README.md, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/asis/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/scanner/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/scanner/RequestMappingScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ViewResolver.java, mvc/src/test/java/nextstep/mvc/controller/scanner/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/controller/scanner/RequestMappingScannerTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/view/ViewResolverTest.java
안녕하세요 디우 👋 레벨2 미션 이후로 디우한테 코드리뷰 받는건 오랜만이네요 ㅎㅎ
처음에 이번 미션을 어떻게 시작해야 할지 감이 잘 안잡혔는데요.. 일단 1단계 요구사항은 만족시킨 것 같아서 제출해 봅니다!! 
구현하다 보니 2단계 요구사항도 일부 구현이 되었는데요.. 문제 있으면 수정하겠습니다 ㅎㅎ 
리뷰 잘 부탁드릴게요 디우도 미션 화이팅하세요 💪
=> [MVC 구현하기 - 1단계] 루키(최지훈) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/handlerAdapter/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handlerAdapter/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handlerAdapter/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handlerMapping/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/handlerMapping/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerExecutionTest.java, mvc/src/test/java/nextstep/mvc/handlerAdapter/AnnotationHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/handlerAdapter/ManualHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/handlerMapping/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java
안녕하세요 아키👋 아리입니다!
구현한 DispatcherServlet의 구조는 다음과 같습니다.
1. request를 통해 handler 찾기
2. handler를 통해 handlerAdapter 찾기
3. handlerAdapter를 통해 ModelAndView 반환받기
4. ModelAndView를 통해 렌더링 실행
이해가 안가는 코드가 있다면 언제든 연락 주세요!
그럼 잘부탁드립니다~! ⭐️
=> [MVC 구현하기 - 1단계] 아리(양유림) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/exception/NotFoundException.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerExecutionTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java
안녕하세요 앤지~! 만나뵙게되어 영광입니다!
최대한 스프링을 따라하지 않으려 했는데 어쩌다보니 실컷 참고했네요 😂
잘 부탁드리겠습니다 🙇🏻‍♂️
=> [MVC 구현하기 - 1단계] 쿼리치(정석윤) 미션 제출합니다.

README.md, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/adapter/ControllerAdapter.java, mvc/src/main/java/nextstep/mvc/adapter/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/adapter/HandlerExecutionAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/adapter/ControllerAdapterTest.java, mvc/src/test/java/nextstep/mvc/adapter/HandlerExecutionAdapterTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java
안녕하세요 클레이! 포키입니다.
스프링 `DispatcherServlet`에 대해 잘 모르다가 이번 기회에 열심히 학습하면서 구현해보았는데요!
아직 모르는게 많아서 부족한 점이 많을 것 같아요.
의견 편하게 남겨주시면 열심히 고민해보겠습니다!
=> [MVC 구현하기 - 1단계] 포키(권예진) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginViewControllerV2.java, mvc/build.gradle, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java, mvc/src/test/java/nextstep/web/support/RequestMethodTest.java, mvc/src/test/java/samples/TestController.java
안녕하세요 코린 잘 부탁드려요
점차 발전해가는 모습 보이겠습니다
=> [MVC 구현하기 - 1단계] 티키(방영호) 미션 제출합니다. 

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/samples/TestController.java, app/src/test/java/samples/TestControllerTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/SimpleControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/MockAnnotationController.java, mvc/src/test/java/nextstep/mvc/controller/tobe/MockController.java, mvc/src/test/java/nextstep/mvc/controller/tobe/SimpleControllerHandlerAdapterTest.java
안녕하세요 짱구! 매트입니다 😃
**🚀 1단계 - @MVC 프레임워크 구현하기** 미션 제출합니다! 
미션을 진행하며 실제 Spring MVC의 동작 구조를 최대한 유사하게 가져가기 위해 참고하였습니다. 덕분에 구조 파악에는 용이 했습니다. 다만 미션 코드 내부에 `HandlerAdapter`의 존재를 확인 한 뒤, `DispatcherServlet에서 HandlerMapping 인터페이스를 활용하여 AnnotationHandlerMapping과 ManualHandlerMapping 둘다 처리`하기 위한 요구사항을 해결하기 위해 `HandlerAdapter` 구현체를 도입하게 되었습니다. 1단계 요구사항의 의도(둘다 처리할 수 있다)를 착각하여 2단계 요구사항을 조금 침범하게 되었네요... 이 부분은 감안하고 리뷰 주시면 감사하겠습니다 🥲
리뷰 잘 부탁드립니다! 감사합니다 🙇‍♂️
=> [MVC 구현하기 - 1단계] 매트(최기현) 미션 제출합니다.

mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/samples/TestController.java
안녕하세요 조시 :) 
주말에 미션을 진행못했다보니 조금 늦게 pr드리게 되었네요 ㅜㅜ
최소한의 요구사항만 구현되어있으며 어뎁터 인터페이스가 있긴한데 2단계 구현사항이라고 판단되어 관련부분은 DispatcherServlet에서 관리하고 있습니다 😄 
크게 두가지 클래스가 구현되어있어 관련부분 코맨트같이 남겨 pr 드립니다 :)
- 기존 `ManualHandlerMapping`만을 제공하던 `getController()`메소드에서 `AnnotationHandlerMapping()`까지 지원할 수 있게끔 메소드를 수정하였습니다.
- 따라서 `Controller`로 캐스팅되어 view를 랜더링하는 부분이 사라졌으므로 `renderView()`라는 해당하는 handler에 맞게 rendering해주는 분기 메소드가 추가되었습니다. (어뎁터 패턴으로 2단계에서 리팩터링 여지가 있을 것 같네요)
- `@Controller` 어노테이션을 가진 클래스에서 `@RequestMapping`어도테이션을 가진 메소드를 관리하는 메소드입니다.
- 의도적으로 for문을 사용하며 stream을 최소화하여 구현되어있습니다. 다른 개발자가 사용하는 프레임워크라는 관점에서 구현된 해당 프레임워크를 사용하는 입장에서 stream을 사용하는 경우 디버깅이 불가능하다라는 관점에서 진행되었습니다.
- `@Controller` 클래스를 찾고 -> `@RequestMapping`이 걸린 메소드를 찾아 -> `path`와 `method`를 가지고 Executions를 구성하는 방식으로 되어있습니다.
- Controller instance를 싱글톤으로 …
=> [MVC 구현하기 - 1단계] 오리(최진영) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/annotation/TestController.java, mvc/src/main/java/nextstep/mvc/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/exception/NotFoundHandlerException.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/exception/NotFoundHandlerAdapterException.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/view/JstViewTest.java, mvc/src/test/java/nextstep/mvc/view/ModelAndViewTest.java
안녕하세요 알렉스! 😁
1단계 요구사항 만족해서 PR 날립니다~
테스트는 뭘 짜야할지 모르겠네요..;
리뷰해주실 때까지 테스트 추가할 수 있으면 추가하고있겠습니다~!
잘부탁드립니다. 🙇
=> [MVC 구현하기 - 1단계] 애쉬(김동호) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/asis/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/controller/asis/ManualHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestAnnotationController.java, mvc/src/test/java/samples/TestManualController.java, mvc/src/test/java/samples/TestManualHandlerMapping.java
안녕하세요. 아서!
1단계 구현해서 제출합니다. 테스트를 어떻게 해야 할 지 막막해서 테스트가 많지 않네요.. 리뷰 해주실 동안 더 고민해보도록 할게요!!
감사합니다.
=> [MVC 구현하기 - 1단계] 클레이(양동주) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/exception/FailMapHandler.java, mvc/src/main/java/nextstep/mvc/exception/FailMapHandler.java, mvc/src/main/java/nextstep/mvc/handlerAdaptor/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handlerAdaptor/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handlerAdaptor/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handlerMapping/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/handlerMapping/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java
레오 안녕하세요~ 제로입니다.
요구사항에 맞게 구현하려고 노력했습니다!
근데 잘 맞는지는 잘 모르겠어요ㅠㅠ 처음에 구조 이해가 많이 어려웠어요! 😢 
잘 부탁드립니다~!
=> [MVC 구현하기 - 1단계] 제로(공재호) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/TestController.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java
안녕하세요 필즈!! 
이렇게 만나게 되니 반갑습니다! 
이번 미션은 1단계 요구사항만 생각하고 구현하였어요!!
Controller 인터페이스를 구현한 컨트롤러(ManualHandlerMapping이 가지고 있는 핸들러), @Controller 어노테이션이 붙은 컨트롤러(AnnotationHandlerMapping이 가지고 있는 핸들러) 의 타입이 다르기도 하고 반환 타입이 달라서 핸들러 어댑터로 구현을 할까 했지만 2단계 요구사항에 있길래 일단 DispatcherServlet에서 반환 타입에 따라 핸들러 메서드를 실행시켜주는 `handle`이라는 메서드를 만들었어요
여러가지 핸들러 타입이 생긴다면 분기가 계속 늘어날테니 이런 부분을 핸들러 어댑터로 추상화해줄 수 있을 것 같아요!
그리고 현재 @Controller이 붙은 클래스를 Reflection으로 불러올 때 `com.techcourse` 부터 하위패키지를 찾고 있는데요! @Controller이 붙은 핸들러가 잘 동작되는지 확인하기 위해서 `com.techcourse.controller` 패키지에 TestController를 추가해놨습니다. /get-test 로 요청을 보내면 index.jsp가 렌더링되는 것을 확인하실 수 있을 것 같습니다!
=> [MVC 구현하기 - 1단계] 쿤(홍동건) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/view/JsonView.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerExecutionTest.java, mvc/src/test/java/nextstep/web/support/RequestMethodTest.java, mvc/src/test/java/samples/TestController.java
안녕하세요 칙촉! 🍪
미션으로나마 오랜만에 만나게되어 반갑네요ㅎㅎ
코드리뷰 잘 부탁드립니다!! 😄
- AnnotationHandlerMappingTest가 정상 동작한다.
- DispatcherServlet에서 HandlerMapping 인터페이스를 활용하여 AnnotationHandlerMapping과 ManualHandlerMapping 둘다 처리할 수 있다.
=> [MVC 구현하기 - 1단계] 유콩(김유빈) 미션 제출합니다. 

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/asis/Controller.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/exception/ControllerCreateException.java, mvc/src/main/java/nextstep/mvc/exception/HandlerAdapterNotFoundException.java, mvc/src/main/java/nextstep/mvc/exception/HandlerNotFoundException.java, mvc/src/main/java/nextstep/mvc/exception/MvcServletException.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/main/java/nextstep/mvc/view/View.java, mvc/src/main/java/nextstep/web/WebApplicationInitializer.java, mvc/src/main/java/nextstep/web/support/MediaType.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapterTest.java
안녕하세요 썬!!
렉스입니다😁
캠퍼스가 달라 못 뵌 지 오래됐는데 이렇게 미션으로 뵙게 되었네요!
구현한 Dispatcher Servlet의 동작 순서는 다음과 같습니다!
1. Dispatcher Servlet이 HandlerMapping리스트에서 요청을 처리해줄 Handler를 반환한다.
2. HandlerAdapter 리스트에서 Handler를 수행할 HandlerAdapter를 찾는다.
3. HandlerAdapter를 실행하여 ModelAndView를 반환받는다.
4. ModelAndView객체를 통해 랜더링을 실행한다.
테스트 코드는 열심히 작성하고 싶었으나..도저히 어떻게 작성해야할지 모르겠어서 작성을 못하였습니다..
다음 단계를 진행하면서도 테스트 코드 작성을 계속 노력해보겠습니다..
리뷰 잘 부탁드립니다!!
=> [MVC 구현하기 - 1단계] 렉스(오성원) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/LogoutController.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/adapter/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/adapter/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/adapter/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/Controller.java, mvc/src/main/java/nextstep/mvc/controller/ForwardController.java, mvc/src/main/java/nextstep/mvc/controller/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/handlermapping/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/handlermapping/HandlerKey.java, mvc/src/main/java/nextstep/mvc/handlermapping/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/adapter/AnnotationHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/adapter/ManualHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/handlermapping/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestAnnotationController.java, mvc/src/test/java/samples/TestManualController.java, mvc/src/test/java/samples/TestManualHandlerMapping.java
안녕하세요 유콩~~!! ☺️☺️☺️
이번 미션 잘 부탁드려요.
체크리스트 2번은 테스트 코드로 동작 여부를 확인 할 수 있게 했는데 적절한 방식인지는 잘 모르겠네요.
=> [MVC 구현하기 - 1단계] 릭(나일성) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java
안녕하세요 마루! 아스핍니다 :)
레벨 2 데일리에 이러 이번 미션 리뷰이로 뵙게 되었네요 😆
아무쪼록 제 작고 부족한 코드 잘 부탁드립니다!
=> [MVC 구현하기 - 1단계] 아스피(신동석) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerAdapter.java, app/src/test/java/com/techcourse/ManualHandlerAdapterTest.java, docs/README.md, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/exception/HandlerAdapterNotFoundException.java, mvc/src/main/java/nextstep/mvc/exception/HandlerInstanceCreateException.java, mvc/src/main/java/nextstep/mvc/exception/HandlerNotFoundException.java, mvc/src/main/java/nextstep/mvc/exception/InvalidMethodException.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapterTest.java
안녕하세요 알파!
미션 구현해서 제출합니다! Adapter 인터페이스가 있어서 만들어야 하는 줄 알았는데, 추후에 해도 되는거더라구요 😢
리뷰 잘 부탁드리겠습니다! 알파도 미션 화이팅하세요~!!
=>  [MVC 구현하기 - 1단계] 썬(윤선용) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java
안녕하세요 후디✋🏻 맞게 한 것인지 좀 모호하네요. 
리뷰 잘 부탁드려요🥲 고생이 많으십니다.
=> [MVC 구현하기 - 1단계] 잉(유영우) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/UserSession.java, app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java, app/src/main/java/com/techcourse/support/web/filter/CharacterEncodingFilter.java, app/src/main/java/com/techcourse/support/web/filter/ResourceFilter.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/asis/ForwardController.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/exception/HandlerAdapterNotFoundException.java, mvc/src/main/java/nextstep/mvc/view/JsonView.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/View.java
안녕하세요 슬로 알린입니다. 
이번 미션 참 열심히 했는데 쉽지않은 미션이었던 것 같습니다 ㅠㅠ...
테스트를 짜려고 짜려고 하다가 도저히 못짜서 일단 제출하고 리뷰를 고치거나 2단계에서 추가해보겠습니다 ㅠㅠ
잘부탁드립니다..!
=> [MVC 구현하기 - 1단계] 알린(장원영) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/LogoutController.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java
=> [MVC 구현하기 - 1단계] 스컬(김윤기) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handlerMapping/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/handlerMapping/ControllerScanner.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/HandlerAdapterRegistryTest.java, mvc/src/test/java/nextstep/mvc/HandlerMappingRegistryTest.java, mvc/src/test/java/nextstep/mvc/controller/asis/ControllerHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerExecutionHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerExecutionTest.java
안녕하세요 아키! 아리입니다~!⭐️
내일이 데모데이라 정신 없으시겠지만 편한 시간에 리뷰를 부탁드려요!👍
원래는 adapter 등이 패키지로 분리되어 있었는데, 요구사항의 클래스 다이어그램에 맞추기 위해 패키지를 다시 통합했어요!
또한, 제가 저번 1단계 때, 받았던 404.jsp 관련 피드백을 적용하지 않았더라구요ㅠㅠㅠ
꼼꼼하게 반영하지 못해 죄송합니다..
현재는 반영한 상태입니다!
이해가 가지 않는 코드가 있다면 언제든 연락 주세요!
그럼 이번 단계도 잘부탁드립니다🙇🏻‍♀️
=> [MVC 구현하기 - 2단계] 아리(양유림) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/SimpleControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/RequestMappingHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/samples/TestController.java
주디 안녕하세요~!😊 마루입니당
처음 구현하기 전에 너무 막막하다보니 DispatcherServlet의 동작 과정에 대해서 많이 찾아보게 됐어요. 
내부 구현은 확인하지 않고 생각대로 구현해봤는데 제대로 된 건지 알쏭달쏭하네요😂 
리뷰 잘부탁드립니다 감사합니다!🙇‍♀️
=> [MVC 구현하기 - 1단계] 마루(송채원) 미션 제출합니다.

README.md, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/adpater/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java
안녕하세요 로마! 또 만났네요😇😇
저번 단계에서 DispatcherServlet에 HandlerAdapter를 구현해놨더니 이번 단계에서 크게 바뀐점이 별로 없네요.
힌트와 클래스 다이어그램도 참고하면서 실제 DispatcherServlet도 뜯어보며 재미있게 진행해봤습니다.
팀프로젝트, 미션, 근로로 많이 바쁠텐데 이번 리뷰도 잘 부탁드리겠습니다🙇‍♀️
로마도 화이팅하세요! 우가우가🔥
=> [MVC 구현하기 - 2단계] 페퍼(최수연) 미션 제출합니다.

mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/test/java/common/FakeManualHandlerAdapter.java, mvc/src/test/java/common/FakeManualHandlerMapping.java, mvc/src/test/java/nextstep/mvc/HandlerAdapterRegistryTest.java, mvc/src/test/java/nextstep/mvc/HandlerMappingRegistryTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java
안녕하세요 렉스!
1단계 때 이미 `HandlerAdapter`를 구현해놓아서 큰 어려움 없이 2단계를 진행했습니다 :)
이번 단계도 잘부탁드려요🙆‍♀️
=> [MVC 구현하기 - 2단계] 아키(허영운) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java
아리아리쓰리쓰리 안녕하세요!
저 짱군데요.
오우... 어렵지만 재밌네요...
늦게 올려서 죄송합니다!
---
아 맞아 `AppWebApplicationInitializer`에서 `AnnotationHandlerMapping`을 추가할 때 "samples"가 아니라 "com.techcourse.controller"로 되어있는데요..! 이게 그 처음엔 모든 컨트롤러에 RequestMapping 적용시켰다가 이게 2단계 요구사항인거 같아서 다시 롤백하면서 못바꾼 것 같네요... 이거 samples로 바꾸고 2단계에서 다시 할까요? 아니면 내비둘까요..!!!
=> [MVC 구현하기 - 1단계] 짱구(신짱구) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/LoginController.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/view/JspView.java
안녕하세요 판다! 열음입니다:)
1단계 요구사항 구현을 마쳐서 PR 날립니다
잘부탁드려요~!
=> [MVC 구현하기 - 1단계] 열음(이주형) 미션 제출합니다.

README.md, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/web/annotation/RequestMapping.java, mvc/src/main/java/nextstep/web/support/RequestMethod.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java
안녕하세요 쿤! 앤지입니다.
이렇게 MVC 미션으로 만나뵙게 되네요 😄 
이번 미션은
두 체크리스트 중심으로 구현했어요! 그럼 리뷰 잘부탁드립니다. 🙇
=> [MVC 구현하기 - 1단계] 앤지(손수민) 미션 제출합니다.

README.md, app/src/main/webapp/WEB-INF/classes/logback.xml, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java
안녕하세요 이스트~! 2단계 제출합니다.
기존에 틀이 있어서 큰 변화는 없는 것 같아요!
리뷰 잘부탁드립니다~!
=> [MVC 구현하기 - 2단계] 기론(김규철) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/handlerAdapter/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/handlerMapping/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/handlerMapping/HandlerMappingRegistry.java, mvc/src/test/java/nextstep/mvc/controller/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/handlerAdapter/HandlerAdapterRegistryTest.java, mvc/src/test/java/nextstep/mvc/handlerMapping/HandlerMappingRegistryTest.java
안녕하세요 제로~
구현하다보니까 commit 단위가 다소 커졌지만... ㅠㅠ 요구사항은 다 구현한 것 같아서 리뷰 요청 드립니다!
이번에도 잘부탁드립니다~😊
=> [MVC 구현하기 - 2단계] 루나(남민정) 미션 제출합니다.

README.md, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/test/java/nextstep/mvc/HandlerAdapterRegistryTest.java, mvc/src/test/java/nextstep/mvc/HandlerMappingRegistryTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java
정 안녕하세요 ~ 
1단계에서 미리 구현한 부분들이 있어, 크게 변경된 점은 없는 것 같습니다! 
이번 리뷰도 잘 부탁드려요 ~ 👍
=> [MVC 구현하기 - 2단계] 그린론(유재서) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java
안녕하세요 마루!! 아스핍니다 :)
1단계에 이어 2단계도 잘 부탁드려요!!
피드백 기다리겠습니다!
=> [MVC 구현하기 - 2단계] 아스피(신동석)미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterAnnotationController.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/adapter/HandlerAdapterRepository.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/mapping/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/mapping/HandlerMappingRepository.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/adapter/ControllerAdapterTest.java, mvc/src/test/java/nextstep/mvc/adapter/HandlerAdapterRepositoryTest.java, mvc/src/test/java/nextstep/mvc/adapter/HandlerExecutionAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/mapping/HandlerMappingRepositoryTest.java, mvc/src/test/java/nextstep/mvc/view/JspViewTest.java, mvc/src/test/java/samples/ManualHandlerMapping.java, mvc/src/test/java/samples/TestAnnotatedController.java, mvc/src/test/java/samples/TestImplementController.java
안녕하세요 클레이!
저번 단계에서 달아주신 리뷰 반영과 함께 2단계 구현 해보았습니다 😸 
리뷰해주신 내용 참고하여 수정한 항목은 다음과 같습니다.
- mock test에서 불필요한 `times(1)` 모두 삭제
- `DispatcherServletTest`에 ManualHandlerMapping 검증 추가
- render 로직 `ModelAndView`로 이동
2단계 요구사항을 구현하고 나서는 `RegisterAnnotationController`를 구현하고 `ManualHandlerMapping`에서 기존의 `RegisterController`, `RegisterViewController`를 삭제하여 Annotation 기반의 handler와 Interface 기반의 handler가 함께 잘 작동하는 것을 확인하였습니다. 이번 리뷰도 잘 부탁드릴게요!
=> [MVC 구현하기 - 2단계] 포키(권예진) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerExecutor.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionHandlerAdapter.java
=> [MVC 구현하기 - 2단계] 슬로(이한울) 미션 제출합니다

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionHandlerAdapter.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/HandlerAdapterRegistryTest.java, mvc/src/test/java/nextstep/mvc/HandlerMappingRegistryTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java, mvc/src/test/java/samples/TestLoginController.java, mvc/src/test/java/samples/TestManualHandlerMapping.java, mvc/src/test/java/support/FakeRequestDispatcher.java
안녕하세요 코린!
조금 더 발전된 모습으로 찾아왔습니다.
잘 부탁드려요
=> [MVC 구현하기 - 2단계] 티키(방영호) 미션 제출합니다. 

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java
안녕하세요 케이~
데모데이 준비도 있었고 예비군사정으로 집에 내려가기도 했어서 PR이 많이 늦어졌네요~
---
++ 6솔!! 케이 대단해요~!!ㅋㅎㅎ
=> [MVC 구현하기 - 2단계] 이프(송인봉) 미션 제출합니다.

app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionAdapter.java, mvc/src/main/java/nextstep/mvc/exception/HandlerAdapterNotFoundException.java, mvc/src/main/java/nextstep/mvc/support/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/support/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/support/HandlerMapping.java, mvc/src/main/java/nextstep/mvc/support/HandlerMappingRegistry.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerExecutionAdapterTest.java, mvc/src/test/java/nextstep/mvc/support/HandlerAdapterRegistryTest.java, mvc/src/test/java/nextstep/mvc/support/HandlerMappingRegistryTest.java
라쿤 안녕하세요! 2단계 구현해서 PR 올립니다!
- ControllerScanner 생성
- handlerMappings, handlerAdapters 일급컬렉션 생성
- DispatcherServlet 리팩터링
이번 리뷰도 잘 부탁드리겠습니다 🙇🏻‍♀️
=> [MVC 구현하기 - 2단계] 코린(유현지)미션 제출합니다.

README.md, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/handlerAdaptor/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/handlerMapping/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/handlerMapping/HandlerMappingRegistry.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/handlerAdaptor/HandlerAdapterRegistryTest.java, mvc/src/test/java/nextstep/mvc/handlerMapping/HandlerMappingRegistryTest.java
레오~ 주말 잘 보내셨나요
2단계 완료했습니다
이번에도 잘 부탁드려요 😄
=> [MVC 구현하기 - 2단계] 제로(공재호) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/asis/ManualHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/support/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/controller/handleradapter/AnnotationHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/handleradapter/ManualHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/handlermapping/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestAnnotationController.java, mvc/src/test/java/samples/TestManualController.java, mvc/src/test/java/samples/TestManualHandlerMapping.java
안녕하세요 이프! 2단계 미션 점진적인 리팩터링을 진행했습니다.
요구사항은 3가지로 ControllerScanner와 HandlerMapping, HandlerAdpater를 관리하는 객체를 생성하는 것이었습니다.
요구사항이기에 반영은 했지만 쓸모가 있는지 잘 모르겠습니다...😅
제가 잘 이해를 못한 것인지 ControllerScanner를 만들면서 Reflections 의존성이 떨어져 나간 것은 좋았으나 그 외에 장점은 무엇이 있을지 잘 모르겠네요. 처음에는 유틸성 클래스로 만들어보려고 하다가 AnnotationHandlerMapping 클래스와 거의 항상 쌍으로 움직이는 것 같아서, basePackage를 가진 Reflections를 필드값으로 들고있도록 구현했습니다. 그러다 보니 오히려 응집도가 떨어지는 코드가 아닌가 하는 의심이 들더라구요. 이프는 구현하시면서 어땠는지 궁금합니다.
추가로) 피드백을 반영하여 `HandlerExecution` 에서 Method를 이용해 Contructor를 받아와 객체를 생성해주도록 했는데, 그러다 보니 매번 handle할 때마다 객체를 생성하게 되더라구요. 생성자에서 instance를 만들어 주려고 하다 CheckedException이 발생하길래 object를 주입받도록 수정했습니다.
=> [MVC 구현하기 - 2단계] 아서(김현태) 미션 제출합니다

README.md, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapterTest.java
안녕하세요 썬!
1단계 미션을 진행하며 `HandlerAdapter`를 미리 구현해서 그런가 2단계 구현을 빠르게 하였습니다.
리펙터링을 진행하면서는 요구사항에 있는 `ControllerScanner `, `HandlerAdapterRegistry`, `HandlerMappingRegistry` 클래스들을 생성하고 클래스 다이어그램에 나와있는 형식과 최대한 유사하도록 코드를 리펙터링했습니다.
이번에도 잘 부탁드립니다😁
=> [MVC 구현하기 - 2단계] 렉스(오성원)미션 제출합니다. 

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/exception/ControllerInstantiationException.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java
주디 안녕하세요!🐰 마루입니다😊
1단계와 비교해 크게 달라진 점은 ControllerScanner, HandlerAdapterRegistry, HandlerMappingRegistry 클래스를 생성해서 기존 로직들의 책임을 분리시킨 점이네요!
2단계 미션 리뷰도 잘부탁드립니다~!🙇‍♀️
=> [MVC 구현하기 - 2단계] 마루(송채원) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutionHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java
리버 안녕하세요!!
2단계 구현이 좀 늦었네요..
LMS의 힌트를 참고해서 2단계 구현했습니다!!
혹시 이해 안되시는 부분 있으면 dm주세요 잘부탁드립니다!
=> [MVC 구현하기 - 2단계] 조시(조현근)미션 제출합니다.

README.md, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java
안녕하세요 레넌!
2단계 요구사항 만족하여 PR 제출합니다.
감사합니다 🙇‍♀️
=> [MVC 구현하기 - 2단계] 봄(장보미) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java
안녕하세요 앤지~ `HandlerMappingRegistry` 와 `HandlerAdapterRegistry` 를 구현하면서 헷갈리는 점이 많았는데요!
현재 `HandlerMapping` 과 `HandlerAdapter` 를 `AppWebApplicationInitializer` 에서 추가해주고 있어요.
그런데 문득 이건 프레임워크가 제공하는 기능이 아닌가? 라는 생각이 들어서 `HandlerMapping` 과 `HandlerAdapter` 의 생성과 추가를 `AppWebApplicationInitializer` 에서 처리하는게 적절한가? 에 대한 의문이 들었어요.
현재까지 이해하기론 해당 프레임워크 사용자가 새로운 커스텀 `HandlerMapping` 과 `HandlerAdapter` 구현체를 추가하여 사용하고 싶을 경우를 대비해 `AppWebApplicationInitializer` 에서 필요에 따라 추가해 사용할 수 있도록 구현된 거라고 이해하고 있습니다.
그렇다면 `ControllerHandlerAdapter` `AnnotationHandlerMapping` `HandlerExecutionAdapter` 등은 mvc 프레임워크에서 제공하는 기능이기 때문에 `DispatcherServlet` 혹은 `HandlerMappingRegistry` `HandlerAdapterRegistry` 내부에서 생성해주어야 할까요?
질문이 너무 장황해진 것 같네여.. ㅎ;
한 줄 요약하자면 
```java
dispatcherServlet.addHandlerMapping(new ManualHandlerMapping()); …
```
=> [MVC 구현하기 - 2단계] 쿼리치(정석윤) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/component/controllerscan/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerMappingRegistry.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java
안녕하세요 쿼리치! 이번 단계에선 클래스 분리해서 역할 분배 해봤습니다!
리뷰 잘 부탁드려요!
=> [MVC 구현하기 - 2단계] 알렉스(이영환) 미션 제출합니다

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/test/java/nextstep/mvc/HandlerAdapterRegistryTest.java, mvc/src/test/java/nextstep/mvc/HandlerMappingRegistryTest.java, mvc/src/test/java/nextstep/mvc/controller/asis/ControllerHandlerAdapterTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java
안녕하세요! 토르
step1 커밋을 그대로 작접하는 바람에 꼬일뻔 했지만 cherry-pick으로 잘 풀어냈습니다 ㅠㅠ
2단계를 너무 늦게 내는 것 같아서 죄송합니다.
이번 미션에서 왜 HandlerAdapterRegistry는 HandlerAdapter를 반환하고
HandlerMappingRegistry는 Optional로 반환하는지 궁금해서 공부해봤는데요
DispatcherServlet에서는 handlerMapping이 null일 경우 noHandlerFound라는 메서드가 동작하게 됩니다.
```java
protected void noHandlerFound(HttpServletRequest request, HttpServletResponse response) throws Exception {
if (pageNotFoundLogger.isWarnEnabled()) {
pageNotFoundLogger.warn("No mapping for " + request.getMethod() + " " + getRequestUri(request));
}
if (this.throwExceptionIfNoHandlerFound) {
throw new NoHandlerFoundException(request.getMethod(), getRequestUri(request),
new ServletServerHttpRequest(request).getHeaders());
}
else {
response.sendError(HttpServletResponse.SC_NOT_FOUND);
}
}
``` …
=> [MVC 구현하기 - 2단계] 승팡(김승래) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, mvc/src/main/java/nextstep/mvc/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapter.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java
안녕하세요 써머~
2단계 늦게 제출해서 죄송합니다 ㅠㅠㅠㅠ
=> [MVC 구현하기 - 2단계] 베루스(정진혁) 미션 제출합니다.

mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/view/ModelAndView.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java
안녕하세요 오리!
2단계는 크게 변경 사항이 있지는 않았던 것 같아요!
우선 요구사항에 맞춰 수정해 보았습니다!
이번 미션도 잘 부탁드립니다 😁
=> [MVC 구현하기 - 2단계] 범고래(조충범) 미션 제출합니다.

mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/test/java/nextstep/mvc/HandlerAdapterRegistryTest.java, mvc/src/test/java/nextstep/mvc/HandlerMappingRegistryTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java
라라! 1단계에서 뭔가를 좀 해놔서... 2단계에서 크게 구현할 게 없었네요...!
리뷰 잘 부탁드립니다!
=> [MVC 구현하기 - 2단계] 크리스(공병주) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, app/src/main/java/com/techcourse/support/web/handler/ManualHandlerMapping.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/handler/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/handler/adapter/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/handler/mapping/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/handler/mapping/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/handler/mapping/RequestMappingScanner.java, mvc/src/test/java/nextstep/mvc/HandlerAdapterRegistryTest.java, mvc/src/test/java/nextstep/mvc/HandlerMappingRegistryTest.java, mvc/src/test/java/nextstep/mvc/handler/mapping/AnnotationHandlerMappingTest.java, mvc/src/test/java/nextstep/mvc/handler/mapping/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/handler/mapping/RequestMappingScannerTest.java
애쉬 안녕하세요! 2단계 리뷰 요청 드립니다.
요구사항에 따라서 `HandlerMappingRegistry`,  `HandlerAdapterRegistry`클래스를 추가하여 `DispatcherServlet`의 책임을 분산시켰고 `ControllerScanner` 클래스를 통해 `AnnotationHandlerMappging`도 `Controller`를 찾는 역할을 하지 않도록 했어요.
이 외에도 자잘한 리팩터링을 진행하였습니다. 항상 좋은 리뷰 감사합니다~
=> [MVC 구현하기 - 2단계] 더즈(이동규) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerMappingRegistry.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java
안녕하세요 쿤! 앤지입니다. 다시 만나뵙게 되었네요 ㅎㅎ!
이번 미션은 
를 중심으로 구현했어요! 그럼 잘부탁드려요!
=> [MVC 구현하기 - 2단계] 앤지(손수민) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/Application.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/domain/User.java, app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java, app/src/main/java/com/techcourse/support/web/filter/CharacterEncodingFilter.java, app/src/main/webapp/login.jsp, app/src/test/java/com/techcourse/ManualHandlerMappingTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerKey.java, mvc/src/main/java/nextstep/mvc/exception/HandlerAdapterNotFoundException.java, mvc/src/main/java/nextstep/mvc/exception/HandlerMappingNotFoundException.java, mvc/src/main/java/nextstep/mvc/view/JsonView.java, mvc/src/main/java/nextstep/mvc/view/JspView.java, mvc/src/main/java/nextstep/web/NextstepServletContainerInitializer.java, mvc/src/main/java/nextstep/web/annotation/PathVariable.java, mvc/src/main/java/nextstep/web/annotation/RequestMapping.java, mvc/src/main/java/nextstep/web/annotation/RequestParam.java, mvc/src/test/java/nextstep/mvc/HandlerAdapterRegistryTest.java, mvc/src/test/java/nextstep/mvc/HandlerMappingRegistryTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java
안녕하세요 슬로 알린입니다.
1단계에서 부족했던 테스트도 요구사항에 맞는 테스트를 추가하였고 요구사항 3개를 만족하도록 수정했습니다.
테스트를 위해 GET /register와 POST /register를 annotation기반으로 돌아가도록 수정했습니다.
이번 미션도 잘부탁드립니다..!
=> [MVC 구현하기 - 2단계] 알린(장원영) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/HandlerExecutor.java, mvc/src/main/java/nextstep/mvc/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/asis/ControllerHandlerAdapter.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecutions.java, mvc/src/main/java/nextstep/mvc/exception/NotFoundException.java, mvc/src/main/java/nextstep/web/exception/NotFoundException.java, mvc/src/test/java/nextstep/mvc/HandlerMappingRegistryTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerExecutionTest.java, mvc/src/test/java/nextstep/mvc/controller/tobe/HandlerExecutionsTest.java
안녕하세요 배카라~~
스프린트 막바지 팀 프로젝트를 진행하느라 미션에 신경을 많이 못 썼네요ㅜㅜ
1단계때 리뷰를 너무 잘해주셔서 2단계 미션은 큰 어려움이 없었습니다!
LMS에 있는 것 처럼 일급컬렉션으로 책임을 분리했습니당
리팩토링을 진행하면서 테스트를 추가해봤어요.
리플렉션, Obejct, Servlet 객체들 때문에 테스트가 쉽지 않았는데요. mock 테스트를 하니 외부 라이브러리에 대한 의존성을 줄어들더라구요. 평소에도 Mock 테스트를 선호하는데 지금 미션같은 경우에 더 힘을 발휘하는 것 같네요! 이번 리뷰도 잘 부탁드려요~!!
저번에 저한테 질문하러오셨는데 평일에 얘기 나눠봐요!! 주말 잘 보내세요~!!!😃😃😃
=> [MVC 구현하기 - 2단계] 호호(유현호) 미션 제출합니다.

app/src/main/java/com/techcourse/AppWebApplicationInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/asis/LoginController.java, app/src/main/java/com/techcourse/controller/asis/LoginViewController.java, app/src/main/java/com/techcourse/controller/asis/LogoutController.java, app/src/main/java/com/techcourse/controller/asis/RegisterController.java, app/src/main/java/com/techcourse/controller/asis/RegisterViewController.java, app/src/main/java/com/techcourse/controller/tobe/ForwardController.java, app/src/main/java/com/techcourse/controller/tobe/LoginController.java, app/src/main/java/com/techcourse/controller/tobe/LogoutController.java, app/src/main/java/com/techcourse/controller/tobe/RegisterController.java, app/src/main/java/com/techcourse/controller/tobe/UserController.java, app/src/main/webapp/index.html, app/src/main/webapp/index.jsp, app/src/main/webapp/login.jsp, app/src/main/webapp/register.jsp, app/src/test/java/com/techcourse/controller/tobe/ForwardControllerTest.java, mvc/src/main/java/nextstep/mvc/DispatcherServlet.java, mvc/src/main/java/nextstep/mvc/controller/registry/HandlerAdapterRegistry.java, mvc/src/main/java/nextstep/mvc/controller/registry/HandlerMappingRegistry.java, mvc/src/main/java/nextstep/mvc/controller/scanner/ControllerScanner.java, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/exception/NotFoundHandlerException.java, mvc/src/main/java/nextstep/mvc/view/JsonView.java, mvc/src/test/java/nextstep/mvc/DispatcherServletTest.java, mvc/src/test/java/nextstep/mvc/controller/registry/HandlerMappingRegistryTest.java, mvc/src/test/java/nextstep/mvc/controller/scanner/ControllerScannerTest.java, mvc/src/test/java/nextstep/mvc/view/JsonViewTest.java, mvc/src/test/java/samples/TUser.java
안녕하세요 디우~~
3단계 미션으로 돌아왔습니다 👋  2단계 때 디우가 꼼꼼하게 리뷰해주셔서 많이 배울 수 있었네요 ㅎㅎ 
3단계도 잘 부탁드릴게요 🥳
추가적으로 요구사항과 살짝 다를 수 있는데, 기존의 `ManualMapping`을 삭제하고 싶지 않아서 주석으로 두고 `com.techcourse.controller.tobe` 패키지에 새로운 `Controller`들을 생성해서 구현하였습니다~
=> [MVC 구현하기 - 3단계] 루키(최지훈) 미션 제출합니다.

.github/workflows/build.yml, mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestMethod.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/View.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/resolver/JspViewResolver.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/resolver/ViewResolver.java, mvc/src/test/java/samples/TestController.java, mvc/src/test/java/web/org/springframework/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerKeyTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/view/JspViewTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/view/resolver/JspViewResolverTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 이리내 
오랜만에 뵙습니다
TestController...관련된 AnnotationHandlerMapping 테스트를 통과시키는걸 잘못 이해해서 삽질을 해서 좀 오래 걸렸네요
리뷰 잘 부탁 드립니다
=> [MVC 구현하기 - 1단계] 지토(김지민) 미션 제출합니다.

.github/workflows/build.yml, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 콩하나! 
콩하나에게 리뷰를 받다니 정말 영광이군요.
잘 부탁드립니다!
=> [Spring MVC 구현] 리오(오영택) 1단계 미션 제출합니다.

mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestMethod.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
이오 안녕하세요! 행록 잘 쓰고 있습니다. 🫡
1단계에서는 어노테이션 기반의 MVC 프레임워크 구현하기까지 완료했습니다!
(2단계 요구사항과 관련되어 있는 것 같아 아직 app 단에는 적용하지 않았습니다)
프레임워크는 다음과 같은 구조로 동작합니다.
1. reflections 라이브러리를 통해 `@Controller` annotation이 있는 클래스를 전부 가져옴
2. 해당 클래스 안에서 `@RequestMapping`annotation이 메서드를 가져와 클래스별로 Grouping
3. 클래스별로 하나의 인스턴스 (변수명 controller)를 생성
4. `@RequestMapping` 안에 지정된 url과 `@Controller`에 지정된 url + RequestMapping의 메서드를 합쳐 ExecutionHandler를 구분하는 키를 생성
5. 각 메서드별로 해당 키와 ExecutionHandler를 매핑(Map에 삽입)
6. 이후 getHandler 메서드가 호출되면 해당 키에 맞는 ExecutionHandler를 반환
제가 이야기해보고 싶은 부분은 다음과 같습니다.
1. reflection을 통해 발생하는 예외는 어떤 클래스에서 처리해줘야 할까?
2. ExecutionHandler를 전부 target으로 Controller 클래스만을 받는데, 그렇다면 이 필드를 Controller 클래스로 지정해도 괜찮을까?
잘부탁드립니다~🙇‍♂️
=> [MVC 미션 1단계] 포이(김보준) 미션 제출합니다. 

mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestMethod.java, mvc/src/main/java/web/org/springframework/web/bind/exception/NotAllowedMethodException.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/exception/HandlerNotFoundException.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/exception/NotFoundHandlerException.java, mvc/src/test/java/web/org/springframework/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 글렌!! 😃 성하입니다!
이번 미션에서 리플렉션을 처음 사용해봐서 조금 헤맸네요 ㅠㅠ
리뷰 잘 부탁드립니다!! ㅎ_ㅎ 🙇🏻‍♂️
=> [MVC 구현하기 - 1단계] 성하(김성훈) 미션 제출합니다.

.github/workflows/build.yml, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/exception/ClassException.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/exception/MethodException.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 제리!
제리가 리뷰이라니 영광 또 영광입니다 ㅎㅎ
코드만 봐도 흐름이 이해되게끔 작성하는 게 목표인터라
비겁하게 PR에 설명하지 않겠습니다.
코드로 이해 안되면 가차없이 조져주십셔.
peace...✨
=> [MVC 구현하기 - 1단계] 준팍(박준현) 미션 제출합니다.

mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 여우! 엔델입니다.
프로젝트에 시간을 쓰다보니 미션의 AnnotationHandlerMapptingTest의 통과에 집중을 한 것 같아요.
코드를 보고 이해가 안되거나 고쳐야할 부분이 있다면 가감없이 말해주세요
감사합니다.
=> [MVC 구현하기 - 1단계] 엔델(김민준) 미션 제출합니다. 

.github/workflows/build.yml, README.md, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/test/java/com/techcourse/domain/UserTest.java, mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestMethod.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/Question.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 제나 ~~ 🌱 
리뷰이 리뷰어로 만나게 돼서 반갑네용
이번 제출 내용에서는 크게 특이 사항이 없어보여서 자세한 설명은 생략하도록 하겠습니다 ㅎㅎ
그래도 의문이 드는 부분이 있다면 편하게 디엠, 질문 주세요~!
가감 없는 리뷰 부탁드려요.. 🤓 감사합니다 !
---
그래도 간단한 작업 내용 공유 드리자면,
- 학습 테스트 작성
- AnnotationHandlerMapping, HandlerExecuter 구현 및 테스트 통과
까지 진행했습니다.
앞으로 주어진 코드에 대한 흐름 이해를 위해 [README](https://github.com/woowacourse/jwp-dashboard-mvc/blob/4ab88a6f9a9c18cc5d9b57503ad8cfeba8865ba7/README.md)에 내용을 작성하며 진행하려고 합니다.
=> [MVC 구현하기 - 1단계] 도이(유도영) 미션 제출합니다.

mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestMethod.java, mvc/src/main/java/webmvc/org/springframework/util/ReflectionUtils.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMethod.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/SpringInitializationException.java
안녕하세요 포이~
1단계 내용 구현하여 리뷰 요청 드립니다!
막상 구현할 내용은 많지 않아 코드가 길지 않네요😅
MVC 미션 잘 부탁드립니다!!
=> [MVC 구현하기 - 1단계] 모디(전제희) 미션 제출합니다.

.github/workflows/build.yml, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DefaultHandler.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 애쉬~
브랜치명을 step1-2로 파버렸는데 수정하는 걸 깜빡해서...무시해주셔도 될 것 같습니다!
그럼 잘 부탁드립니다👐
=> [MVC 구현하기 - 1단계] 아마란스(송세연) 미션 제출합니다.

mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요, 파워 ~! 1단계 리뷰 요청 보냅니다!
테스트 통과를 목적으로 AnnotationHandlerMapping 클래스를 완성시키는데 집중했습니다!
추가적으로, 구현하면서 예외 처리에 대해 고민했던 점이 있어 아래 남깁니다 ㅎㅎ
```
controllerClass.getDeclaredConstructor().newInstance();
```
위 메서드를 실행할 때 여러 가지의 CheckedException이 발생합니다.
(`NoSuchMethodException`, `InvocationTargetException`, `InstantiationException`, `IllegalAccessException`)
이 때 이를 예외로 처리해서 던질지 혹은 충분히 발생 가능한 예외로 봐야할지 고민했는데요,
저는 해당 예외들은 `Controller.Class`를 모두 가져왔지만, 해당 클래스 내부의 메서드 구현 여부로 인해 발생하는 문제로 충분히 발생 가능한 예외들이라고 봤습니다. 또한, 해당 예외들은 다른 `Controller.Class` 들을 매핑하는데 영향을 주지 않아야 한다고 생각했습니다. 그래서 try~catch로 핸들링하고 아무 예외도 던지지 않고 무시하도록 구현하였는데요 ..! 
관련해서 파워의 생각도 듣고 싶습니다 ㅎㅎ 
이번 mvc 미션 잘 부탁드립니다 🙇‍♂️🙇‍♂️
=> [MVC 구현하기 - 1단계] 라온(문채원) 미션 제출합니다.

mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
=> [MVC 구현하기 - 1단계] 도치(김동흠) 미션 제출합니다. 

README.md, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerKey.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
조이 안녕하세요!
리뷰어로 만나게 되다니 새롭네요..!ㅎㅎ
리뷰 잘부탁드리고 앞으로도 잘부탁드립니다~!
=> [MVC 구현하기 - 1단계] 채채(신채원) 미션 제출합니다.

mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionTest.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 로이스!!
오랜만이네용. 잘 부탁 드립니다!!
- Reflection API 학습 테스트 통과
- `AnnotationHandlerMappingTest`의 테스트 통과
=> [MVC 미션 1단계] 연어(황재현) 미션 제출합니다.

mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 우가!
우가를 리뷰어로 만나다니 영광입니다 ㅎㅎ
일단 1단계는 요구사항이 많지 않아 이렇게 했습니다! 리뷰 잘 부탁드려요~~~!
=> [MVC 구현하기 - 1단계] 에코(조은찬) 미션 제출합니다.

mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestMethod.java, mvc/src/main/java/web/org/springframework/web/exception/RequestMethodNotFoundException.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 블랙켓 ㅎㅎ
리뷰 잘부탁드립니다 ㅎㅎㅎㅎㅎㅎ 🐈
=> [MVC 미션 1단계] 케로(김지현) 미션 제출합니다.

README.md, mvc/src/main/java/nextstep/mvc/controller/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/nextstep/mvc/controller/tobe/HandlerExecution.java, mvc/src/test/java/nextstep/mvc/controller/tobe/AnnotationHandlerMappingTest.java, study/src/test/java/reflection/Junit3Test.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 마쓔
1단계는 최대한 간단하게 진행했어요
마지막에 `HandlerExecution`의 `handle()` 메서드가 어떻게 `ModelAndView` 객체를 반환해야 할지에 대해서 
도저히 모르겠어서 다른 크루 3인의 코드를 참고한 결과 모두 아래와 같이 그냥 강제 캐스팅을 해버리더라고요!
```java
public ModelAndView handle(final HttpServletRequest request, final HttpServletResponse response) throws Exception {
return (ModelAndView) method.invoke(controller, request, response);
}
```
일단 테스트 코드가 깔끔히 성공하길래 그냥 이렇게 두긴 했으나...
저는 아직도 왜 이게 강제 캐스팅에 깔끔히 성공하는지 모르겠습니다....
마쓔가 혹시 안다면 저에게 설명해주심 감사하겠습니다.... 👉🏻👈🏻
=> 깃짱의 MVC 구현 1단계 🌟

mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 오도~ 주디입니다!
오도랑은 처음 얘기 나눠보네요 ㅎㅎ 반갑습니다~
이번 리뷰 잘 부탁드립니다!! 🔥🔥🔥
=> [MVC 구현하기 - 1단계] 주디(오은비) 미션 제출합니다

mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestMethod.java, mvc/src/main/java/web/org/springframework/web/bind/exception/InvalidRequestMethodException.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/exception/InvalidClassException.java, mvc/src/test/java/web/org/springframework/web/bind/annotation/RequestMethodTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 아코!
커밋이 많지 않고 커밋 간 변동 사항이 많지 않아서 커밋별로 보시면 더 편할 것 같아요.
리뷰 잘 부탁드립니다~
=> [MVC 구현하기 - 1단계] 엔초(권예진) 미션 제출합니다. 

.github/workflows/build.yml, mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestMethod.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/test/java/samples/TestController.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/SharedCounterServlet.java, study/src/test/java/reflection/Junit3Test.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/Question.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/reflection/Student.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 두둠! 레벨1 인터뷰 이후로 오랜만에 뵙네요.
그럼 MVC 구현하기 미션 리뷰 잘 부탁드립니다 🐶
이번 1단계를 진행하며 공유하고 싶은 사안은 다음과 같습니다. `AnnotationHandlerMapping`과 관련된 내용들 뿐인데요.
1. AnnotaionHandlerMapping안에 있는 basePackage 필드의 타입이 Object[]인 이유를 공부해보고 싶어 주석으로 남겨두었습니다.
2. 미션 요구사항에는 없지만 @RequestMapping 애노테이션이 클래스 레벨에도 붙을 수 있음을 고려하여 AnnotationHandlerMapping#initialize에, 최종 url과 methods을 결정하는 로직을 포함했습니다.
3. AnnotationHandlerMapping의 코드와 메서드를 조금 더 간결하게 할 수 있을 것 같은데, 바로 생각이 잘 안나더라구요 🥲
혹시 두둠이 보셨을 때, 더 개선할 수 있을 포인트가 있다면 알려주시면 감사하겠습니다 !!
리뷰하실 [커밋](https://github.com/woowacourse/jwp-dashboard-mvc/pull/428/commits/3b98ae583059ff4c29856437ae8f7dd83a98672d)입니다!
=> [MVC 구현하기 - 1단계] 도기(김동호) 미션 제출합니다.

mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 망고!
레벨 인터뷰 이후로 다시 뵙게되어서 반갑습니다ㅎㅎ
실력이 부족하여 겨우 테스트만 돌아가게끔 구현을 했네요ㅠ
시간 괜찮으실 때 리뷰해주시면 감사하겠습니다!
수고하세요!
=> [MVC 구현 1단계] 로이(김덕우) 미션 제출합니다.

mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/exception/ControllerClassNotFoundByNameException.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/exception/ReflectionInstantiationException.java
안녕하세요 채채😊
Reflection 관련 코드들이 주를 이루는 미션이였던 것 같아 학습 테스트 모두 진행 한 뒤 코드 작성했습니다!!
구조적인 것은 2단계에서 같이 대화 나눠보면 좋을 것 같아요오!!👍
=> [MVC 구현하기 - 1단계] 스플릿-박상현 미션 제출합니다. 

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginController.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/ModelAndView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
=> [MVC 구현하기 - 1단계] 오도(문민혁) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/support/web/handler/adaptor/HandlerAdaptors.java, app/src/main/java/com/techcourse/support/web/handler/adaptor/ManualHandlerAdaptor.java, app/src/main/java/com/techcourse/support/web/handler/adaptor/ManualHandlerMappingWrapped.java, app/src/main/java/com/techcourse/support/web/handler/mapping/HandlerMappings.java, app/src/test/java/com/techcourse/support/web/handler/adaptor/HandlerAdaptorsTest.java, app/src/test/java/com/techcourse/support/web/handler/adaptor/ManualHandlerAdaptorTest.java, app/src/test/java/com/techcourse/support/web/handler/mapping/HandlerMappingsTest.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/HandlerAdaptor.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdaptor.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdaptorTest.java
안녕하세요 박스터~! 좋은 리뷰 부탁드립니다🙌
이번 미션에서는 `DispatcherServlet`이 `Annotation Controller`가 호환되게 하는데에 집중 했습니다! `JsonView`가 호환되는 건 다음 단계 요구사항인 것 같아서 `JspView`만 호환되게 만들었어요! 
제 `DispatcherServlet`의 로직의 흐름은 다음과 같습니다.
1. `HandlerMapping`을 통해 `Handler`를 찾아옴.
2. `Handler`에 따른 `HandlerAdaptor`를 찾아옴. `HandlerAdaptor`는 `Handler`가 `Object` 타입이기 때문에 형변환을 통해 실행될 환경을 제공
3. `HandlerAdaptor`를 통해 `Handler`를 실행해서 `ModelAndView`를 찾아옴.
4.  `ModelAndView`의 `View`와 `Model`을 통해 렌더링을 하여 response를 만들음
spring에서는 `ViewResolver`를 사용하던데 저희는 `ModelAndView` 객체가 `View`를 필드로 직접 가지고있어서 굳이 필요없을 것 같다는 생각이 들었습니다. 그럼 좋은 리뷰 부탁드립니다💪
=> [MVC 구현하기 - 2단계] 두둠(최영훈) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/ManualHandlerMappingAdapter.java, app/src/main/java/com/techcourse/controller/AnnotatedRegisterController.java, mvc/src/main/java/webmvc/org/springframework/util/ReflectionUtils.java, mvc/src/main/java/webmvc/org/springframework/util/ReflectionUtilsException.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/DispatcherServlet.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/SpringInitializationException.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/AbstractView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
안녕하세요 포이~ 2단계 내용 구현하여 리뷰 요청 드립니다
비슷한 고민을 많이 하셨을 것 같은데 제가 고민했던 부분을 말씀드리고 의견을 나누면 좋을 것 같아요!
1단계를 진행할 때는 Spring MVC와 동일한 구조로 프레임워크를 만들어야 할까 생각했었어요.
이번 단계를 진행하면서는 사실 그보다는 기존의 레거시인 `app` 패키지의 클래스들을 어떻게 최소한으로 수정할까를 더 고민했습니다.
`app`쪽 클래스를 건드리는 것과 `mvc`쪽 클래스를 건드리는 것은 완전히 별개의 작업으로 보았습니다.
- `ManualHandlerMapping`을 그대로 두고 `mvc`의 `HandlerMapping`을 상속한 `ManualHandlerMappingAdapter`를 만들어 레거시 코드와 무관하게 프레임워크가 `ManualHandlerMapping`을 온전히 활용하도록 했습니다.
- 프레임워크가 프레임워크에 맞는 서블릿을 제공해야 한다고 생각해 `mvc`에 새로운 `DispatcherServlet`을 만들고 사용했습니다.
구조에 대해서는 적절한지 계속 고민중이라 포이 코드도 보고.. 구구가 올려주신 힌트도 보면서 계속 고민해볼게요~
의견 많이 주시면 감사하겠습니다!
=> [MVC 구현하기 2단계] 모디(전제희) 미션 제출합니다. 

.github/workflows/build.yml, app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/test/java/com/techcourse/DispatcherServletTest.java, app/src/test/java/com/techcourse/ManualHandlerMappingTest.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandler.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/Handler.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/ManualHandler.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
로이스 안녕하세요!
아래의 작업들을 했습니다.
잘 부탁드려요😃
- 두 `ManualHandlerMapping`, `AnnotationHandlerMapping`을 `HandlerMapping` 인터페이스로 추상화
- 두 `Controller`와 `HandlerExecution`을 `Handler` 인터페이스로 추상화
- `DispatcherServlet`은 `List<HandlerMapping>`를 참조하고 적절한 `Handler`를 찾아서 실행시키도록 변경
유저의 요청이 들어오면 위의 과정들을 `DispatcherServlet#service`에서 처리합니다.
```java
@Override
protected void service(final HttpServletRequest request,
final HttpServletResponse response) throws ServletException {
// 적절한 핸들러 얻기
final Handler handler = handlerMappings.stream()
.filter(handlerMapping -> handlerMapping.supports(request))
.findAny()
.orElseThrow()
.getHandler(request);
// 유저의 요청 처리
handler.handle(request, response);
}
```
=> [MVC 구현하기 - 2단계] 연어(황재현) 미션 제출합니다. 

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, app/src/main/java/com/techcourse/controller/TestController.java, app/src/main/webapp/test.jsp, app/src/test/java/com.techcourse/DispatcherServletTest.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/View.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/ControllerAdopter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdopter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdopters.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionAdopter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMappings.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
dispatcher servlet 공부하면서,
최대한 비슷하게 하려고 했는데, 잘된건진 모르겠네요.
이번 리뷰도 잘 부탁드립니다 베베~
=> [mvc 2단계] 폴로 미션 제출 합니다.

.github/workflows/build.yml, app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/ModelAndView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/View.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/HandlerAdapters.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/HandlerMappings.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/asis/ControllerHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationScanner.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/asis/ControllerHandlerAdapterTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionHandlerAdapterTest.java
안녕하세요 토리
이번 2단계에서는 레거시 controller도 동작하도록 추상화를 통해 만들어 보았습니다.
조금 맘에 들지 않는 부분은 dispatcher servlet에서 adapter를 찾아 adapter를 실행시켜주는 부분인데 좋은 생각 공유 부탁드립니다!
=> [MVC 2단계] 박스터 미션 제출합니다

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/test/java/com/techcourse/ManualHandlerMappingTest.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/ModelAndView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/View.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapters.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMappings.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/ManualHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapterTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdaptersTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/ManualHandlerAdapterTest.java
안녕하세요 그레이! 디노입니다~🦕
step2 제출이 생각보다 늦었네요.. 
사실 2단계 구현의 범위가 어디까지인지도 모호해 우선 Mapping과 Adapter를 인터페이스로 추상화 하여 Manual과 annotation 모두 적용 가능하도록 하는 정도까지 완료했습니다!
새로 생성한 클래스들의 패키지 위치를 app으로 해야 할 지 mvc로 해야 하는지 잘 모르겠지만 우선 app이 legacy이고 mvc가 새로 작업하는 부분이라고 생각해 우선 mvc 내에 위치시켰습니다. 클래스의 위치에 대해 그레이의 의견 듣고 싶어요!
테스트도 최대한 작성해 보려 했는데, DispatcherSevlet은 어떻게 테스트 해야할지 아직 감이 오질 않네요..
그레이는 어떻게 하셨는지 궁금합니다..!
부족한 부분이 정말정말 많을텐데 가감 없이 코멘트 남겨 주시면 감사하겠습니다!!🙇
=> [MVC 구현하기 - 2단계] 디노(신종화) 미션 제출합니다 

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/HandlerAdapterFactory.java, app/src/main/java/com/techcourse/HandlerMappingFactory.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/test/java/com/techcourse/DispatcherServletTest.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/ModelAndView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/View.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMappingPackages, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/ManualHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/samples/TestController.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapterTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/src/test/java/di/stage3/context/DIContainer.java, study/src/test/java/di/stage4/annotations/ClassPathScanner.java, study/src/test/java/di/stage4/annotations/DIContainer.java
안녕하세요, 루쿠!
`ManualHandlerMapping` 과 `AnnotationHandlerMapping` 이 하는 일은 같지만 실행하는 메서드들이 달라서, 어댑터 패턴을 적용해보았습니다.
대략적인 플로우는 다음과 같습니다.
1. `DispatcherServlet` 의 `init` 메서드 호출 시, `HandlerMapping` 리스트와 `HandlerAdapter` 리스트를 초기화합니다.
2. `service` 가 호출되었을 때, 해당 요청에 맞는 handler (`HandlerExecution` 혹은 `Controller`) 를 가져옵니다.
3. adapter 리스트 중에 해당 handler 를 처리할 수 있는 adapter 가 있는지 확인합니다.
4. 처리할 수 있는 adapter 가 존재하면 `handle` 을 호출하여 메서드를 실행합니다.
5. 리턴받은 `ModelAndView` 를 `move` 메서드로 처리합니다.
이번 미션에서 문제가 되었던 점은 테스트를 수행하기 매우 어렵다는 점입니다... `DispatcherServlet` 의 BASE_PACKAGE_PATH 를 주입해줄 방법을 찾지 못해 결국 테스트를 만들지 못했습니다... 😭 
스프링 코드 상에서는 `DispatcherServelt` 의 `initialize` 에서 빈들을 가져오는데요, 이때 `Context` 가 자동으로 찾아서 넣어주고 있습니다.
그러나 제 코드에서는 빈이 없기 때문에, BASE_PACKAGE_URL 을 주입해주는 주체가 누구여야 하는지 고민이 됩니다.
이 부분을 중점적으로 코드 리뷰 받고 싶습니다!
혹시나 플로우가 …
=> [MVC 구현하기 - 2단계] 베로(김은솔) 미션 제출합니다.

app/build.gradle, app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/handlerMapper/AnnotationHandlerAdapter.java, app/src/main/java/com/techcourse/handlerMapper/AnnotationHandlerMapping.java, app/src/main/java/com/techcourse/handlerMapper/HandlerAdapter.java, app/src/main/java/com/techcourse/handlerMapper/HandlerMapping.java, app/src/main/java/com/techcourse/handlerMapper/ManualHandlerAdapter.java, app/src/main/java/com/techcourse/handlerMapper/ManualHandlerMapping.java, app/src/test/java/com/techcourse/handlerMapper/AnnotationHandlerAdapterTest.java, app/src/test/java/com/techcourse/handlerMapper/ManualHandlerAdapterTest.java, app/src/test/java/samples/TestController.java, mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestMethod.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
깃 장 안녕하세요ㅎㅎ
조금 늦게 pr 올리게 됐네요
저번에 리뷰 주신 부분도 추가 반영해서 기능 구현해 봤어요
좋은 리뷰 부탁드립니다~~
=> [MVC 구현하기 - 2단계] 하마드(이건회) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/test/java/com/techcourse/DispatcherServletTest.java, app/src/test/java/com/techcourse/controller/RegisterControllerTest.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/View.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/asis/Controller.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DispatcherServlet.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/Handler.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMappings.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/NotFoundHandler.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/NotFoundHandlerTest.java
안녕하세요 하디!
이번 코드에서 구조를 간단하게 설명드릴게요.
- Controller와 handlerExecution을 Handler라는 인터페이스로 추상화 했습니다.
-  ModelAndView handle(request,response) throws Exception;
- AnnotationHandlerMapping, ManualHandlerMapping을 HandlerMapping이라는 인터페이스로 추상화를 했어요.
- void initialize()
- Handler getHandler(request)
흐름은 다음과 같아요
- DispatcherServlet.service(request, response) 호출
- HandlerMappings를 통해 입력받은 request에 해당하는 handler 조회
- handler의 handle 메서드 실행
- View 출력
view의 경우에는 JspVIew를 구현하려 했으나, 3단계 요구사항이어서 단순하게 viewName을 반환하는 정도에서 구현을 마무리 했습니다.
저번에 남겨주신 리뷰가 꼼꼼해서 좋았습니다. 
이번에도 잘 부탁드려요!!
코드를 잘 이해하지 못하시겠다 하시는 부분은 언제든지 dm으로 편하게 연락주세오
=> [MVC 구현하기 2단계] 홍실(홍혁준) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerAdapter.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, app/src/main/webapp/login.jsp, app/src/test/java/com/techcourse/DispatcherServletTest.java, app/src/test/java/com/techcourse/ManualHandlerAdapterTest.java, app/src/test/java/com/techcourse/ManualHandlerMappingTest.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/ModelAndView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/View.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapterRegistry.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMappingRegistry.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/samples/TestController.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMappingRegistryTest.java, study/src/test/java/di/stage3/context/DIContainer.java, study/src/test/java/di/stage3/context/Stage3Test.java, study/src/test/java/di/stage4/annotations/ClassPathScanner.java, study/src/test/java/di/stage4/annotations/DIContainer.java
안녕하세요 하마드 오랜만입니다
handlermapping과 handleradapter 인터페이스를 통해 패키지 의존성을 관리하고 annotation, controller를 상속하는 방식 모두 작동하도록 구현했습니다
테스트를 좀 철저하게 짜고 싶은데 쉽지 않네요.
어떤 부분에 테스트가 있으면 더 좋을지 코멘트 해주시면 감사하겠습니다
=> mvc step2 주드 미션 제출합니다

README.md, app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/ModelAndView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/View.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
안녕하세요 우가..
데모데이 잘 준비하고 계신가요? 저는 이번 데모데이 준비로 미션을 제대로 못하고 있는거 같아 아쉽고 슬픕니다.. ㅠ 미션 정말 재미있는데 프로젝트에 치여서 순위가 밀렸네요,, 그래서 사실 힌트대로 하지도 않았고 필요가 없다고 생각되는 것들은 굳이 만들지 않았습니다. step3하면서 필요한 부분은 리펙토링 해보려구요!
아무튼 우가 지난 리뷰감사드리고 아래에 리뷰 답변 달아두었습니다. 이번에도 잘 부탁드려요!
1. 핸들러 키를 생성할 때 path 가 request mapping 만을 사용하신 이유가 궁금합니다!
→ 생각해보니 Controller어노테이션이 붙은 Controller에서도 RequestMapping이 사용될 수 있겠다는 생각이 들었습니다! 하지만 시간 관계상 일단은 간단하게 구현해보것 같아요!
2. Controller 어노테이션에도 path 가 존재하고 있어서 이부분은 어느 객체에서 붙여주어 사용하면 좋을지도 궁금합니다!
→ 앗 이부분도 우가가 알려주셔서 알았는데, 사실 사용하고 있는 부분이 딱히 없어서 붙여주진 않았습니다. 다만 방금 얘기했듯 Controller 클래스에 @RequestMapping 어노테이션이 붙는다면 그곳에서는 추가로 path를 붙여줄 것 같네요! 아예 보지도 못했었는데 감사합니다 ㅎㅎ
3. handle 이 호출될 때 유동적으로 Object 를 만들어 주면 되지 않을까?
→ 저도 처음에는 매서드를 호출할때 Object를 만들어줬었다가 교체해줬는데요, 저는 모든 컨트롤러 인스턴스를 만드는게 물론 자원낭비일  순 있지만, 그래도 처음 만들어두고 요청이 올때마다 …
=> [MVC 구현하기 - 2단계] 에코(조은찬) 미션 제출합니다. 

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/ManualHandlerAdapter.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapterRegistry.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMappingRegistry.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
안녕하세요. 망고!
'Handleradapter'와 'HanlderMapping'을 인터페이스로 구현하는 2단계 미션을 진행해봤습니다.
충분히 고민하고 구현을 해보고 싶었지만, 그러질 못했네요ㅠ
시간나실 때 천천히 리뷰해주시면 감사하겠습니다!
5차 데모데이도 화이팅입니다!
=> [mvc구현 / 2단계] 로이(김덕우) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/HandlerAdapterRegistry.java, app/src/main/java/com/techcourse/HandlerMappingRegistry.java, app/src/main/java/com/techcourse/ManualHandlerAdapter.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/LogoutController.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, app/src/main/java/com/techcourse/controller/UserSession.java, app/src/main/java/com/techcourse/lagacy/controller/LoginController.java, app/src/main/java/com/techcourse/lagacy/controller/LoginViewController.java, app/src/main/java/com/techcourse/lagacy/controller/LogoutController.java, app/src/main/java/com/techcourse/lagacy/controller/RegisterController.java, app/src/main/java/com/techcourse/lagacy/controller/RegisterViewController.java, app/src/main/java/com/techcourse/lagacy/controller/UserSession.java, app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java, app/src/main/java/com/techcourse/support/web/filter/CharacterEncodingFilter.java, app/src/main/java/com/techcourse/support/web/filter/ResourceFilter.java, mvc/src/main/java/core/org/springframework/util/ReflectionUtils.java, mvc/src/main/java/web/org/springframework/web/bind/annotation/PathVariable.java, mvc/src/main/java/web/org/springframework/web/bind/annotation/RequestParam.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
안녕하세요 여우, 엔델입니다. 개인 일정 상 미션 구현이 늦어져서 죄송합니다,,
기본적으로, DispatcherServlet에서 HandlerMappingRegistry와 HandlerAdapterRegistry를 사용하고 있습니다.
그리고 서버를 켠 후에 요청이 들어오면 핸들링할 수 있는 핸들러를 get한 다음 실행하여 처리합니다.
이때 기존의 핸들러와 어노테이션이 붙은 핸들러의 간극은 adapter를 이용해 처리하는 것으로 구현했습니다.
리뷰 잘 부탁드립니다. 감사합니다.
=> [MVC 구현하기 - 2단계] 엔델(김민준) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/RegisterController.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/asis/ControllerHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handler/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handler/HandlerAdapters.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handler/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handler/HandlerMappings.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
안녕하세요 스플릿!
2단계 요구사항이었던, 레거시 MVC와 어노테이션 기반의 MVC가 공존할 수 있도록 수정해보았습니다.
제가 맞이했던 문제들과, 그 문제를 어떻게 풀어내려 했는지는 아래와 같습니다.
레거시 핸들러와, 어노테이션 핸들러가 있는 상태에서, 각각의 핸들러가 처리할 수 있는 요청은 정해져 있었습니다.
생각해볼 수 있는 가장 심플한 방법은, '들어온 요청에 대해 모든 핸들러를 돌아보며 `getHandler()` 를 호출해보고, 그 결과로 나온 Handler 를 반환하기' 입니다.
이를 구현하기 위해 `HandlerMapping` 에 대한 일급 컬렉션을 만들었고, 그에 대한 코드는 아래와 같습니다.
```java
public Object getHandler(final HttpServletRequest request) {
for (final HandlerMapping handlerMapping : handlerMappings) {
final Object handler = handlerMapping.getHandler(request);
if (handler != null) {
return handler;
}
}
throw new IllegalArgumentException("Handler Not Found");
}
```
요청에 대한 적절한 핸들러를 찾았지만, 그 핸들러는 `Controller` 일수도, `HandlerExecution` 일수도 있습니다.
또한, 각각 메서드명도 다르고, 반환하는 타입도 다른 상황이었습니다.
- `Controller` 스펙
```java
String …
```
=> [MVC 구현하기 - 2단계] 코코닥(이승용) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/HandlerAdapters.java, app/src/main/java/com/techcourse/HandlerMappings.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/LogoutController.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/asis/ControllerHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
조이 안녕하세요! 제출이 늦었습니다..ㅠㅠ
이번 리뷰도 잘부탁드립니다!
=> [MVC 구현 2단계] 채채(신채원) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerProcessor.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
안녕하세요 로건!
빠르게 리뷰해주셨는데 2단계 제출에 시간이 좀 걸렸네요;; 
잘 부탁드립니다~
=> [MVC 구현하기 2단계] 도치(김동흠) 미션 제출합니다. 

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/HandlerAdaptor.java, app/src/main/java/com/techcourse/HandlerAdaptors.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/exception/HandlerFieldException.java, app/src/main/java/com/techcourse/exception/NoSuchHandlerFoundException.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/ModelAndView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/View.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
안녕하세요 레오! 리뷰 늦어져서 죄송합니다;;;
이번 단계에서 생각한 것은 기존 레거시코드 (ManualHandlerMapping)을 최대한 건들지 않는 선에서 RegisterController만 어노테이션 기반의 코드로 바꿀려고 노력해 보았습니다.
그 과정에서 내부 Handler를 갖는 List의 이름을 controllers로 바꾸어 주었는데 이를 가져오는데 reflection으로 field를 가져왔습니다. 뭔가 캡슐화가 깨지는것 같아 마음에 들지 않지만 ManualHandlerMapping을 건들지 않는 선에서 한다는게 힘들더라고요.... 레오는 어떤 방식을 사용하셨나요?
=> [MVC 구현하기 2단계] 달리(김동연) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/HandlerAdapters.java, app/src/main/java/com/techcourse/HandlerMappings.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/ManulHandlerAdapter.java, app/src/main/java/com/techcourse/controller/annotation/TestController.java, app/src/main/java/com/techcourse/controller/legacy/LoginController.java, app/src/main/java/com/techcourse/controller/legacy/LoginViewController.java, app/src/main/java/com/techcourse/controller/legacy/LogoutController.java, app/src/main/java/com/techcourse/controller/legacy/RegisterController.java, app/src/main/java/com/techcourse/controller/legacy/RegisterViewController.java, app/src/main/java/com/techcourse/controller/legacy/UserSession.java, app/src/test/java/ApplicationTest.java, app/src/test/java/com/techcourse/domain/UserTest.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/ModelAndView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/samples/TestController.java
안녕하세요 히이로! 🏋️‍♀️
2단계 마치고 리뷰요청 드려요
처음에는 스프링 내부의 코드를 조금씩 훑어보려했는데, 워낙 크기가 방대해서 어디까지 봐야하는지... 좀 헷갈리더라구요
그래서 아래 사진을 보고, 제 맘대로 만들어봤습니다😋
1. DIspathcerServlet에서 HandlerMapping을 통해 핸들러를 찾습니다
2. 위에서 찾은 핸들러를 처리할 수 있는 어댑터를 HandlerAdapter를 통해 찾아와요
3. 어댑터를 통해 해당 요청을 핸들링 한 다음, ModelAndView를 반환합니다
4. ModelAndView에서 해당 내용만 렌더링합니다.
뷰 관련된 처리는 3단계 내용인 것 같지만..
JsonView를 들어간 순간 TODO와 눈이 마주쳐서 이친구만 옮겨줬습니다ㅎㅎ..
프로젝트로 바쁘실텐데, 천천히 해주셔도 됩니다!
=> [MVC 구현하기 2단계] 가비 미션 제출합니다. 

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/test/java/com/techcourse/DispatcherServletTest.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/ModelAndView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/View.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
안녕하세요 코코닥
2단계 미션도 잘 부탁드립니다!!!
1단계 리뷰들도 같이 적용했는데 코멘트 주신 것들 중 한 개는 제가 제대로 이해를 못 해서 재질문드렸습니다. 그 부분도 확인 해 주셨으면 합니다😀😀
=> [MVC 구현하기 - 2단계] 썬샷(오진택) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/HandlerMappings.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandler.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DefaultHandler.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DefaultHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/Handler.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapters.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/MannualHandler.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/ManualHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionTest.java
안녕하세요 애쉬~ 2단계도 잘 부탁드립니다!
구현에 대한 설명을 덧붙이자면 1단계에서 구현한 AnnotationHandlerMapping과 주어진 MannualHandlerMapping를 HandlerMapping이라는 인터페이스로 추상화를 했구요, HandlerMapping의 getHandler가 반환하고 있는 Handler는 Controller 클래스와 HandlerExecution 클래스를 추상화한 인터페이스입니다.
미리 리뷰 감사드립니다~!
=> [MVC 구현하기 - 2단계] 아마란스(송세연) 미션 제출합니다

app/src/main/java/com/techcourse/ControllerHandlerAdapter.java, app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/HandlerAdapterRegistry.java, app/src/main/java/com/techcourse/HandlerMappingRegistry.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/annotation/HomeController.java, app/src/main/java/com/techcourse/controller/annotation/LoginController.java, app/src/main/java/com/techcourse/controller/annotation/LogoutController.java, app/src/main/java/com/techcourse/controller/annotation/RegisterController.java, app/src/main/java/com/techcourse/controller/legacy/LoginController.java, app/src/main/java/com/techcourse/controller/legacy/LoginViewController.java, app/src/main/java/com/techcourse/controller/legacy/LogoutController.java, app/src/main/java/com/techcourse/controller/legacy/RegisterController.java, app/src/main/java/com/techcourse/controller/legacy/RegisterViewController.java, mvc/src/main/java/web/org/springframework/web/exception/HandlerMappingNotFoundException.java, mvc/src/main/java/web/org/springframework/web/exception/InvalidHandlerTypeException.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/ModelAndView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/asis/Controller.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/asis/ForwardController.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
안녕하세요 오리
오: 오랜만입니다.
리: 이렇게 뵙게 되어 반갑습니다.
1단계 머지 이후로 2단계 제출까지 너무 오랜 시간이 걸렸네요 .. 아직 레벨4의 스케줄에 적응하지 못한 것 같습니다 ㅎㅎ;;
이번 단계는 힌트를 적극 참고했습니다. 조금 더 고민할 시간을 가졌다면 좋았을텐데 아쉬움이 남습니다. 힌트를 참고했더라도 부족한 부분이 있을 테니 사소한 부분이라도 짚어주시면 감사하겠습니다.
리뷰 잘 부탁드리겠습니다 오리~ 감사합니다!
=> [MVC 구현하기 - 2단계] 민트(유재민) 미션 제출합니다. 

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/webapp/login.jsp, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/asis/ManualHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/asis/ManualHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerAdapters.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMappings.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java
안녕하세요..  말랑 🙇‍♂️
프로젝트하면서 해야지.. 해야지.. 하고 있다가 이제 겨우 제출하네요..
일단 어떻게 돌아가는지만 파악하고 구현했습니다..
=> [MVC 구현하기 2단계] 호이(이건호) 미션 제출합니다. 

app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/LogoutController.java, app/src/main/java/com/techcourse/controller/UserController.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DefaultHandler.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DefaultHandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/DispatcherServlet.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerMappings.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionTest.java
=> [MVC 구현하기 - 3단계] 아마란스(송세연) 미션 제출합니다. 

app/src/main/java/com/techcourse/ControllerAdapter.java, app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/View.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlermapping/HandlerAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/handlermapping/HandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/mvc/tobe/HandlerExecutionAdapter.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JsonView.java, mvc/src/main/java/webmvc/org/springframework/web/servlet/view/JspView.java, mvc/src/test/java/webmvc/org/springframework/web/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
안녕하세요~ 아마란스
늦은 시점에 별로인 코드로 제출하게 됐네요..ㅋㅋㅋ
엄청난 규모를 생각하고 리팩토링을 하다가 어제 밤에 홈 폴더를 삭제하는 바람에 (sudo rm -rf ~)..
일단 급하게 구현해서 제출합니다 흑흑
양해 부탁드립니다..
=> [MVC 구현하기 - 2단계] 에밀(김대희) 미션 제출합니다

mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/ForwardController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 로빈~ 이번에 처음으로 리뷰어로서 만나게 됐네요 😇
1단계 @MVC 프레임워크 구현하기 기능 요구 사항에 맞춰 미션을 진행했습니다.
의도에 맞게 잘 했는지는 정확히 모르겠으나,
제가 어떤 의도로 코드를 작성했는지 주석을 남겨두었습니다.
코드를 읽을 때 참고가 되길 바라며 미리 감사드립니다. 🙇🏽‍♂️
=> [MVC 구현하기 - 1단계] 이상(이건상) 미션 제출합니다.

mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/ModelAndView.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/Controller.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/ForwardController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerFinder.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/Handler.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerFinderTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerTest.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
구름☁️~☁️~☁️~☁️~☁️~☁️~ 안녕하세요. 망쵸입니다~
구름을 리뷰어로 만나는 날이 오네요 😀 우테코 오래하고 볼 일이에요
아주 잘 부탁드려요! 
1단계는 기본에 충실하고자 노력했어요. 미션이 아직 감이 안 와서 lms에 있는 사항을 충실하게 구현하고 테스트했어요. 
꼼꼼하게 코드 작성하려 노력 중인데, 놓친 부분이 있다면 언급해 주세요! 
테스트하면 좋을 부분, 빠뜨린 부분, 객체 간의 책임을 중점적으로 봐주시면 감사하겠습니다 🙇(아톰이 자주 쓰는 이모지)
=> [MVC 구현하기 - 1단계] 망쵸(김주환) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 뽀로로 ~ 🐧
학습 테스트와 1단계 요구사항 구현하여 리뷰 요청드립니다 🙇🏼‍♂️
노는게 제일 좋은 추석 잘 보내시고 천천히 리뷰 해주셔도 됩니다 ~! 😄
=> [MVC 구현하기 - 1단계] 카키(서현준) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/util/TestController.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요, @nayonsoso 산초! 리뷰어 관계로 만나게 되어 반갑습니다 ✋🏻 
1단계 요구사항에 집중해서 구현을 했습니다. 
잘 부탁드립니다 😄 
- Reflection API 학습테스트 진행
- AnnotationHandlerMappingTest 클래스 테스트 통과하기
-  reflection을 통해서 basePackage에 존재하는 Controller 어노테이션이 붙은 핸들러 가져오기
- getHandler를 통해 적절한 핸들러 반환하기
- DispatcherServlet의 로직 JSPView로 옮기기
- 관련 테스트 생성
=> [MVC 구현하기 - 1단계] 초코칩(권기호) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/NotFoundException.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutions.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyExtractor.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionsTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyExtractorTest.java, mvc/src/test/java/samples/TestController.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 포케!
1단계 구현 마치고 리뷰 요청 보냅니다!
리뷰는 천천히 연휴 즐기고 달아주셔도 괜찮아요!
추석 잘 보내고 리뷰 잘 부탁드립니다!
=>  [MVC 구현하기 - 1단계] 비토(오상훈) 미션 제출합니다.

mvc/src/main/java/com/interface21/web/SpringServletContainerInitializer.java, mvc/src/main/java/com/interface21/web/bind/annotation/PathVariable.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestParam.java, mvc/src/main/java/com/interface21/webmvc/servlet/View.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/ForwardController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyGenerator.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyGeneratorTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyTest.java, mvc/src/test/java/support/TestHttpServletRequest.java, mvc/src/test/java/support/TestHttpServletResponse.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/reflection/Student.java
안녕하세요 타칸 ✈️  포케입니다!
이번 2번째 미션에서 특별히 리뷰 받고 싶은 부분은 아래와 같아요 😃 
```
1. 객체간 책임 분리가 어색하면 말씀부탁드려요
2. 네이밍이 모호하거나 명확하지 않으면 훈수 부탁드립니다
3. 학습 테스트 개념 중 좀 더 학습하면 좋은 것들이 있다면 마음껏 공유 부탁드립니다 🙏  
```
그럼 2번째 미션 잘 부탁드립니다 😄
감사합니다
=> [MVC 구현하기 - 1단계] 포케(이무송) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/webapp/index.jsp, mvc/src/main/java/com/interface21/web/SpringServletContainerInitializer.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotatedHandlerRegistry.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyCreator.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotatedHandlerRegistryTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyCreatorTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/SampleController.java, mvc/src/test/java/samples/TestController.java, study/src/test/java/reflection/Junit3Test.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요. 🖐️ 조이썬
캠퍼스가 나뉘고 못본지 오래됐네요. 
이렇게 미션으로 만나뵙게 되니 느낌이 색다르네요. 😀
MVC 구현 미션 화이팅해봅시다 🔥
LMS에서 제공한 미션 요구사항은 만족했지만, 무엇을 의도하는지 조금 혼란스러운 상태입니다. 혹시 코드를 보시다가 이상하다싶으면 미션 이해를 제대로 못했을 확률이 높으니 해당 부분 짚어주면 적극 반영하겠습니다. 
사소한 컨벤션이나 일관성이 떨어지는 부분을 최소화하고자 노력하겠지만, 이런부분보다 객체지향적인 구조와 올바른 스펙 사용에 대해 더 중점적으로 리뷰해주시면 도움이 될것 같아요 👍
=> [MVC 구현하기 - 1단계] 프람(김민종) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/core/util/ReflectionUtils.java, mvc/src/main/java/com/interface21/web/SpringServletContainerInitializer.java, mvc/src/main/java/com/interface21/web/bind/annotation/PathVariable.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestParam.java, mvc/src/main/java/com/interface21/webmvc/servlet/View.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/ForwardController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlingException.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 아톰! 리뷰이 명오입니다.
리플렉션을 이번 미션에서 처음 활용해봐서 조금 고생했네요.
얘가 알고 쓴걸까? 싶은것들도 질문해주시면 좋을 것 같습니다.
리뷰와 별개의 궁금증이 있다면 DM 주시면 감사하겠습니다!
잘 부탁드립니다~
=> [MVC 구현하기 - 1단계] 명오(김형호) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/TomcatStarter.java, mvc/README.md, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/UncheckedServletException.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/BeanFactory.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/test/java/reflection/Junit3Test.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 카고!! 처음 뵙네요 😀
이번 미션 목표는 Spring MVC 프레임워크를 구현하는 것인데
이전에 혼자 아키텍처를 학습한 경험이 있어서, 1단계 기능 요구 사항을 만족하는 데는 크게 어렵지 않았던 것 같아요.
그래서 이번 단계를 구현하는 동안
기능 요구 사항 문서를 미리 작성하고, 테스트 작성, 로그를 잘 기록하는 일처럼 기본기에 더 신경을 기울여보았습니다 😊
원하실 때 편하게 리뷰 남겨주세요!
감사합니다.
=> [MVC 구현하기 - 1단계] 재즈(함석명) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, docs/README.md, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 켬미! 이번엔 리뷰이가 된 폭포입니다. 😄 
`1단계 @MVC 프레임워크 구현하기` 미션 구현 완료해서 PR 보냅니다.
각각의 구현한 기능별로 테스트를 작성해서, 기능이 올바르게 동작하는지 확인해봤습니다.
구현한 흐름대로 커밋을 작성했기 때문에, 커밋 순서대로 따라가셔도 괜찮을 것 같아요. 양이 그렇게 많은 편이 아니라 한 번에 보셔도 문제 없지만요 ㅎㅎ. 커밋 순서 상으로 중간에 `JspView`를 구현한건, `JspView`를 구현해야 `AnnotationHandlerMappingTest`가 돌아가는 것으로 착각했기 때문입니다. 😓 나중에 알고보니 아예 별개였네요.
리뷰 부탁드립니다. 감사합니다. 🙇
=> [MVC 구현하기 - 1단계] 폭포(이성주) 미션 제출합니다

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/NotSupportMethodException.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/ModelAndView.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerContainer.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/DuplicateHandlerKeyException.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/FailHandlerExecuteException.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/FailInstanceCreateException.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/NotFoundConstructorException.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerContainerTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/SampleController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/CanonicalInterface.java, study/src/test/java/reflection/ExceptionClass.java, study/src/test/java/reflection/FieldTest.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/reflection/Room.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 감자! 🥔 
예전 테코톡 준비할때 같이 얘기한 이후로, 되게 오랜만 이네요 ☺️
구구의 의도대로 코드를 작성한지 잘 모르겠네요
( 코드도 꽤나  🗑️ 입니다. 에궁,, 🥲🥲 )
신경쓴 부분으로는
리플렉션을 사용하며 발생하는 `Checked Exception` 을 전파하지 않기 위해 객체간 분리 & 역할에 대해 신경을 쓴거 같습니다.
개념적인 내용이나 학습 테스트에서 의아한 부분 & 궁금한 부분에 대한 질문 & 코드에 대한 질문 뭐든 좋습니다! ☺️☺️
잘 부탁드리겠습니다! 🫡🫡
=> [MVC 구현하기 - 1단계] 조이썬(이영수) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/Model.java, mvc/src/main/java/com/interface21/webmvc/servlet/ModelAndView.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutions.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/InstancePool.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionsTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/InstancePoolTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요. 배키 이번 미션 리뷰이 위브입니다.
리플렉션 러닝테스트와 1단계 구현 했습니다.
아직 흐름이 완벽하게 이해된 것 같지는 않습니다.
메타인지 향상을 위한 질문 형태의 리뷰도 환영입니다.!
많이 배우겠습니다.
=> [MVC 구현하기 - 1단계] 위브(김기범) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/FilterTest.java, study/src/test/java/servlet/com/example/ServletTest.java
반갑습니다 <img src="https://emoji.slack-edge.com/TFELTJB7V/moly/cdc41a6e3758ade4.jpg" height=20></img>
첫 페어 이후로 미션에서는 오랜만에 보네요🙂
리뷰 잘 부탁드립니다~
=> [MVC 구현하기 - 1단계] 페드로(류형욱) 미션 제출합니다

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutions.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 다온👋🏻👋🏻
잘 지내셨나요? 🤗 
레벨 4 참 바쁠텐데 천천히 리뷰 부탁드려요!
감사합니다 ⍢
=> [MVC 구현하기 - 1단계] 릴리(최윤서) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/NoHandlerFoundException.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/src/main/java/servlet/com/example/KoreanServlet.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 클로버 🍀
이렇게 리뷰어로 보니 반갑네요ㅎㅎ
잘 부탁드려요~~
이번 1단계 미션은 `AnnotationHandlerMappingTest` 가 통과하면 미션을 완료한 것으로 이해했습니다. 
테스트 코드를 통과했지만, 미션에서 의도한 것을 만족했는지가 의문입니다... 혹시 이상한 부분 있으면 꼭 말씀해 주세요!
=> [MVC 구현하기 - 1단계] 배키(백은희) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/ModelAndView.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/invalidsamples/DuplicateController.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요, 에버! 👋
처음 인사드리는 것 같네요! 😄
레벨 4 미션과 프로젝트, 병행 잘 하고 계시나요?
저는 조금 힘든 것도 같습니다..
리뷰 잘 부탁드립니다!
=> [@MVC 구현하기 - 1단계] 리건(이한길) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 제제! 🍊
타칸입니다!😊
스터디 이후로 오랜만에 코드 리뷰를 받게 되었네요! ㅎㅎ
리플랙션은 처음이라 조금 어색한 부분이 있을 수 있는데 더 개선될 방향이 있으면 알려주시면 감사하겠습니다!
잘 부탁드려용
=> [MVC 구현하기 - 1단계] 타칸(최원준) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, docs/requirements.md, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 백호! 👋
MVC 구현하기 미션으로 만나게 되어 정말 반가워요. 😄
리뷰 잘 부탁드립니다!
=> [MVC 구현하기 - 1단계] 제우스(신재우) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/LocalCounterServlet.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 도비!! 반갑습니다! 🙇‍♂️
연휴에 잘 쉬고 계신가요?
1단계를 완료해서 미션 제출합니다!
편하실때 천천히 리뷰 부탁드립니다.
감사합니다. 😊
=> [MVC 구현하기 - 1단계] 로키(정해성) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/controller/LoginController.java, docs/README.md, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ConstructorGenerator.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/all/TestController.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ConstructorGeneratorTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeyTest.java, mvc/src/test/java/duplicate/DuplicateMappingController.java, mvc/src/test/java/samples/PrivateCrew.java, mvc/src/test/java/samples/PublicCrew.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/KoreanServlet.java, study/src/main/java/servlet/com/example/ServletApplication.java, study/src/test/java/reflection/Junit3Test.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4Test.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 폴라!! 
이렇게 코드리뷰로 만나는건 처음이군요 ㅎ.ㅎ 
리플렉션 api를 직접 사용해본건 이번 미션이 처음이였습니다. 그래서 올바르게 쓰지 못한 부분들이 있거나 하면 따끔하게 혼내주세요. 사실 그동안 리플렉션 위험하니까 쓰지마세요라는 글을 많이 봤었는데 재밌는거 혼자만 쓰려고 그랬던것 같네요 😑
리뷰 잘부탁드립니다ㅏ
=> [MVC 구현하기 - 1단계] 레디(최동근) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/Question.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 트레! 리뷰이 콜리입니다 🥦 
이번 미션은 난이도를 느끼기에 앞서 생소한 개념이 많아 혼란스러웠던 것 같아요.
그래도 이해한 바대로 요구사안에 충실하려 노력했습니다.
몇가지 구현과 관한 전달사안은 다음과 같습니다.
- method 미지정 시 모든 method를 지원하라는 요구사안에 맞추어 RequestMapping 의 default로 모든 RequestMethod를 배열에 담아주었습니다.
- AnnotationHandlerMapping : Controller가 달린 클래스 탐색 > RequestMapping 어노테이션 탐색 > url + method 같은지 비교 를 통해 handling 가능한 method를 탐색하고 있습니다.
- JspView의 경우 활용은 다음 단계라 생각해 render 메서드는 mocking을 통해 슬라이스 테스트를 진행하였습니다.
MVC 미션 잘 부탁드립니다 🙇 
[학습 테스트 커밋 범위](https://github.com/woowacourse/java-mvc/pull/669/commits/51d2a61be2a358878751f23770169e498405bd63)
[RequestMapping TEST 구현 커밋 범위](https://github.com/woowacourse/java-mvc/pull/669/files/51d2a61be2a358878751f23770169e498405bd63..0177afef323327eff829e93c1c3c4006842eed3c)
[JspView 구현 커밋 …
=> [MVC 구현하기 - 1단계] 콜리(김건우) 미션 제출합니다

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요, 레모네! 클로버입니다 🍀 
캠퍼스가 갈라진 뒤로 못보고 있었는데 잘 지내고 계신가요?
이렇게 만나니까 반갑네요 😄 
테스트 코드를 최대한 작성해보긴 했으나 부족할 수도 있을 것 같아요.
혹시 보완할 곳이 보인다면 바로 말해주세요!
MVC 구현하기 미션 기간동안 잘 부탁드려요 🙇
=>  [MVC 구현하기 - 1단계] 클로버(이은정) 미션 제출합니다

mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요, 페드로! 리뷰이 우주입니다.
이래저래 바쁜 나날을 보내다보니 1단계 미션을 늦게 제출하게 됐네요;;
잘 부탁드리겠습니다!
=> [MVC 구현하기 - 1단계] 우주(김성현) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/View.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/ForwardController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeys.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKeysTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/Question.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/FilterTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 조조!
추석은 잘 보내셨나요?
이번 MVC 미션 1단계를 완료하여 리뷰를 요청합니다.
몇 가지 질문 사항이 있는데, 코멘트로 남겨두겠습니다.
감사합니다!
=> [MVC 구현하기 - 1단계] 메이슨(김경원) 미션 제출합니다

mvc/src/main/java/com/interface21/context/BeanCreationException.java, mvc/src/main/java/com/interface21/context/BeanFactory.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/context/BeanFactoryTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, mvc/src/test/java/samples/TestController1.java, mvc/src/test/java/samples/TestController2.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 짱수! 오랜만입니다 잘 지내시나요? ㅎㅎㅎ
학습테스트는 Reflection 테스트, 오늘 진행한 Servlet 테스트까지 이번 PR에 포함되어 있습니다
이번 미션동안 잘 부탁드려요 감사합니다 😊
=> [MVC 구현하기 - 1단계] 프린(남기범) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ClassInstantiator.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ClassInstantiatorTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
반갑습니다 🚨 알파카 🚨
이렇게는 또 처음이네요 ㅎㅎ
리뷰 잘 부탁드립니다!
=> [MVC 구현하기 - 1단계] 몰리(김지민) 미션 제출합니다

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/docs/README.md, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestController.java, study/docs/README.md, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 냥인~~ 추석 잘 보내셨나요??
프로젝트와 지난 미션에 시달리다가 이제야 겨우 1단계를 구현해서 제출하네요😂
리플렉션이라던가, MVC 프레임워크의 구조라던가 이런건 그동안 들어만 봤지 제대로 공부해본 건 이번이 처음이라 부족한 부분이 정말정말 많을 것 같습니다.
각 클래스들이 어떤 책임을 지녀야 하는 지도 잘 모르겠고, 값을 서로서로 어떤 형태로 주고받아야 하는지도 잘 모르겠네요ㅎㅎ
편하게 리뷰해주시면 감사드리겠습니다 👍
이번 미션 잘 부탁드립니다.
=> [MVC 구현하기 1단계] 초롱 미션 제출합니다!!

README.md, app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요, 새양! 🐦🐑
리브입니다. 🍀
MVC 구현하기 1단계 미션 완료하여 제출합니다!
즐거운 주말에 새양이 편하게 쉴 수 있게 더 빨리 제출하고 싶었는데 테코톡 이슈...로 늦어진 점 양해 부탁 드립니다 😭😭😭😭
리뷰하다 궁금한 점이 있으시면 언제든지 편하게 DM 주세요! 👍
ps. 새양 리뷰 맛 기대할게요 ㅋㅋㅋㅋㅋ
=> [MVC 구현하기 - 1단계] 리브(김민주) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/DispatcherServletInitializer.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/MvcViewResolver.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/ViewResolver.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/type/JsonView.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/type/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/MvcViewResolverTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 상돌~
미션 구현 완료하여 리뷰요청 드립니다!
처리해볼만한 부분 있다면 남겨주시면 확인하고 반영해보겠습니다 잘 부탁드립니다~!
=> [MVC 구현하기 - 1단계] 이든(최승준) 미션 제출합니다

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/README.md, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 초롱✨
1단계 구현했고, 구현 내용은 README 참고하심 됩니다!
즐거운 추석 연휴 보내세요~🌕
=> [MVC 구현하기 - 1단계] 조조(조은별) 미션 제출합니다.

README.md, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutions.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 콜리! 제리입니다
편하게 리뷰 남겨주세요! 잘 부탁드립니다
=> [MVC 구현하기 - 1단계] 제리(김민정) 미션 제출합니다.

app/build.gradle, mvc/build.gradle, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/samples/TestController.java, study/build.gradle, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 마크 ! 이번엔 제가 리뷰이가 되었네요 ㅎㅎ 또 만나게 되어서 반갑습니다 ☺️
Reflection 학습 테스트를 진행하고 1단계 요구 사항을 구현했습니다. 잘부탁드려요 🙇🏻‍♀️
=> [MVC 구현하기 - 1단계] 미아(이종미) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutions.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/ViewName.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionsTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/ViewNameTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/KoreanServlet.java, study/src/main/java/servlet/com/example/LocalCounterServlet.java, study/src/main/java/servlet/com/example/SharedCounterServlet.java, study/src/test/java/reflection/Junit3Test.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/FilterTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 커찬! 아슬아슬하게 리뷰 요청 드리네요..! 리뷰 잘 부탁 드려요!
=> [MVC 구현하기 - 1단계] 켈리(양성욱) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/Question.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 테드, 켬미입니다 😊 
접점이 없어서 이야기를 못해봤는데 이렇게 리뷰어-리뷰이로 만날 수 있어서 좋네요 !
이번 미션은 어떻게 시작할지 감이 안잡혀서 막막했어요 ㅜ 그래도 학습테스트를 토대로 "AnnotationHandlerMappingTest 클래스의 테스트 성공"에 충실하게 코드 구현하였습니다 !
모르는 부분이 많으니 거침없이 리뷰해주세요 ~!
=> [MVC 구현하기 - 1단계] 켬미(김경미) 미션 제출합니다

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
메이슨 안녕하세요~ 바쁘셨을텐데 주말은 잘 보내셨나요?
1단계 요구사항은 모두 구현한 것 같아 일단 1차 제출 드려요~
이번주도 화이팅입니다🫡
=> [MVC 구현하기 - 1단계] 상돌(이상진) 미션 제출합니다.

mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 이상! 이번 MVC 구현하기 미션을 함께하게 된 알파카입니다 🙇 
제가 코드 중간 중간에 학습을 위한 용도로 주석을 함께 남기고 있어서 조금 지저분해 보일 수도 있는데 너무 심하다 싶으시면 말씀해 주세요!
그럼 이번 미션 리뷰 잘 부탁드립니다!!
=> [1단계 - @MVC 구현하기] 알파카(최휘용) 미션 제출합니다. 

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 폭포! 호기입니다!
분명 저번 미션에선 반대였던 것 같은데,, 이렇게 되었네요..?!
잘부탁드립니다!
=> [MVC 구현하기 - 1단계] 호기(조호연) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
아토, 안녕하세요. 냥인입니다. 😸
일단 요구사항은 만족했는데, 아직 mvc에 대한 이해도가 많이 떨어집니다. 하하. 😅
테스트도 잘 작성했는지 모르겠네요.
리뷰 잘 부탁드립니다.
시간 날 때 천천히 해주셔도 됩니다.  ◠‿◠
남은 연휴도 즐겁게 보내세요.
=> [MVC 구현하기 - 1단계] 냥인(최가희) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 애쉬 🙇‍♂️
주어진 요구사항 만족을 최우선으로 진행하였습니다.
어떠한 피드백이든 환영입니다 🔥
잘부탁드리겠습니다 !
- `JspView` 클래스 테스트
- 단위 테스트에서 `JSP` 파일이 실제로 존재하고 렌더링되는지 확인하는 것은 어려워, 
서블릿 요청 및 응답을 모킹하여 테스트하였습니다.
- `@RequestMapping()`에 method 설정이 되어 있지 않으면 모든 HTTP method 지원 테스트
=> [MVC 구현하기 - 1단계] 호티(윤주호) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
위브 안녕하세요! 아토입니다.
우테코 시작할 때 자바 초심자... 당연히 스프링도 초심자... 였던 입장에서
이해하려고 노력하며 구현을 해보았습니다.
데모데이에 테코톡, 테크니컬 라이팅까지 눈코 뜰 새 없이 바쁘네요 🥹
수업시간에 했던 학습테스트들까지 포함되어있으니 이 pr에서 함께 봐주시면 됩니다!
=> [@MVC 구현하기 - 1단계] 아토(이혜린) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/View.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/Controller.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/ForwardController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionException.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 프람~~! 러쉬입니다. 만나서 반갑습니다. 
1단계 요구사항에 맞춰서 미션 진행했습니다. 
리플렉션을 처음 사용해봐서 어렵네요..ㅎㅎ
- 요구사항 충족
- 객체지향
에 대해 봐주시면 감사하겠습니다🙇🏻‍♂️
미션 관련 질문 남겨주셔도 좋습니다!
리뷰 잘 부탁드려요~~
=> [MVC 구현하기 - 1단계] 러쉬(이태훈) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/README.md, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/exception/NotFoundController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/FilterTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 시소! 
이전 미션에서 시소의 리뷰어로 만났었는데, 이제는 리뷰이가 되었네요ㅎㅎㅎㅎ😄
이번 미션도 잘 부탁드립니다!
=> [MVC 구현하기 - 1단계] 레모네(이지현) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/NotFoundController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/DefaultController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestController.java, study/src/test/java/com/example/TestClass.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 테바 🐼
페어 프로그래밍 굉장히 즐겁게 했던 기억이 있는데, 리뷰어-리뷰이로 다시 만나게 되어 기쁘네요!
처음부터 깔끔하게 코드를 작성하지 않아서 그런지, 메서드 분리가 어색한 부분이 있다고 느껴지네요.
전반적으로 조금이라도 어색한 부분 있으면 피드백 부탁드립니다!
=> [MVC 구현하기 - 1단계] 트레 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/ModelAndView.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
잉크 안녕하세요! 처음으로 인사 드리네요 😊
재미있게 의견 나눠봐요~ 잘 부탁드립니다!
=> [MVC 구현하기 - 1단계] 땡이(정지호) 미션 제출합니다

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4Test.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java, 기능명세서.md
=> [Step1] 테바의 MVC 구현하기 제출합니다!

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutions.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/ServletApplication.java, study/src/main/java/servlet/com/example/SharedCounterServlet.java, study/src/main/java/servlet/com/example/TomcatStarter.java, study/src/test/java/reflection/Junit3Test.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4Test.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/reflection/Student.java, study/src/test/java/servlet/com/example/ServletTest.java
호티 안녕하세요
종이라고 합니다 처음 인사드려요~🙇
JSP가 디스패처로 포워딩이 되고 있다는건 알겠는데 실제 렌더링이 어떻게 되고 있는지 아직 감이 안잡히네요..
1단계에 비하면 API편의성이 엄청 올라간거 같네요!
코드를 좀 더 분석해봐야할듯..
리뷰 잘부탁드립니다!
=> [MVC 구현하기 - 1단계] 종이(최우종) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandler.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/test/java/com/techcourse/ManualHandlerMappingTest.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandler.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/Handler.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
도비 안녕하세요! 🤗 
2단계 미션 제출합니다!
> 변경이 쉽지 않기 때문에 기존 코드를 유지하면서 신규 기능을 추가해야 한다.
이 요구사항을 가장 중요하게 생각하여 기존 레거시 컨트롤러 코드를 유지하도록 작업했습니다.
리뷰 잘 부탁드립니다! 👍
=> [@MVC 구현하기 - 2단계] 로키(정해성) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 재즈! 폰드입니다🙇‍♂️
이렇게 만나뵙게 되서 반갑네요!
리뷰 잘 부탁드리겠습니다.
=> [MVC 구현하기 - 1단계] 폰드(권규택) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 우주! 🌠
이렇게 만나게 되었네요
방끗 😊 웃는 주말 보내시길 바랍니다
=> [MVC 구현하기 - 1단계] 시소(신지송) 미션 제출합니다. 

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 도라~
이번에 처음 리플렉션을 활용해보며 코드를 짜봤는데, 생각보다 쉽지 않네요..ㅎㅎ
이번 미션 잘 부탁드립니다!!~
=> [MVC 구현하기 - 1단계] 뽀로로(조경찬) 미션 제출합니다.

mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/view/JspViewTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 카키 :>
미션으로 뵙게 되서 반갑습니다!
이번 미션은 꽤나 생소한 개념들이라 코드를 제대로 작성했는가에 대해 자신감이 없네요..ㅎㅎ
함께 의논해보면서 리뷰 이어나갔으면 좋겠습니다!
리뷰 잘 부탁드려요 :)
=> [1단계 - @MVC 프레임워크 구현하기] 도비(김도엽) 미션 제출합니다.

mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 레디~! 이번 MVC 구현하기 미션 리뷰이 마크입니당
이번 학습 테스트와 단계를 통해 처음 리플렉션을 사용해봤고 애너테이션과 함께 어떤 방식으로 MVC가 구현될 수 있는지 감을 잡아가고있어요. 잘부탁드려요~!
=> [MVC 구현하기 - 1단계] 마크(김승현) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/test/java/com/techcourse/DispatcherServletTest.java, mvc/src/main/java/com/interface21/webmvc/servlet/handleradapter/ControllerHandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/handleradapter/HandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/handleradapter/RequestMappingHandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/test/java/com/interface21/webmvc/servlet/handleradapter/ControllerHandlerAdapterTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/handleradapter/RequestMappingHandlerAdapterTest.java, mvc/src/test/java/samples/TestAnnotationController.java, mvc/src/test/java/samples/TestController.java
안녕하세요, 레모네! 클로버입니다. 🍀 
이번 단계에서는 Controller 기반과 어노테이션 기반의 핸들러 둘 다 동작 가능하도록 수정하는 코드를 작성했습니다.
테스트를 위해 `RegisterController`가 어노테이션 기반으로 변경됐으니 참고 부탁드려요 🙇 
남은 기간 동안도 잘 부탁드립니다!
- `getModel()`이 비어있을 경우 render 하지 않는 로직은 제거 되었습니다. `model`이 비어있어도 뷰가 렌더되는 상황이 있다고 판단했기 때문입니다. 
Ex) `LoginController`의 `login` 메서드
=> [MVC 구현하기 - 2단계] 클로버(이은정) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/ModelAndView.java, mvc/src/main/java/com/interface21/webmvc/servlet/exception/NotFoundHandlerAdapterException.java, mvc/src/main/java/com/interface21/webmvc/servlet/exception/NotFoundHandlerException.java, mvc/src/main/java/com/interface21/webmvc/servlet/handler/ControllerHandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/handler/HandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/handler/HandlerExecutionHandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/handler/HandlerExecutor.java, mvc/src/main/java/com/interface21/webmvc/servlet/handler/HandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/handler/HandlerMappingRegistry.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/handler/ControllerHandlerAdapterTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/handler/HandlerExecutionHandlerAdapterTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/handler/HandlerExecutorTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/handler/HandlerMappingRegistryTest.java, mvc/src/test/java/samples/TestController.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 리비! 옆 팀 커찬입니다.
프로젝트 때문에 바쁘실텐데 servlet 학습 테스트를 포함하여 2단계 리뷰 부탁드립니다!
추가로 궁금하신 사항 있다면 DM 주시거나 직접 찾아와주세요!
=> [MVC 구현하기 - 2단계] 커찬(이충안) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/web/bind/annotation/RequestMethodTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/OutputTestExtension.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java, study/src/test/java/servlet/com/example/FilterTest.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 호기! 미션으로 만나게 되어 반갑습니다😊
리뷰 받고 싶은 부분들은 아래와 같습니다.
저는 이번 단계를 아래와 같이 해석했습니다.
```
1. @MVC Framework 테스트 통과하기
- 리플렉션을 활용해서 
- @Controller가 붙은 클래스를 찾고
- 그 클래스에서 @RequestMapping이 붙은 메서드를 찾은 다음,
- RequestMapping 정보를 HandlerKey로, 메서드를 HandlerExecution로 만든 뒤
- 이들을 map 으로 저장하는 AnnotationHandlerMapping를 구현하기
=> 핵심은 리플렉션 이해하기 & 구현 능력 높이기?!😵‍💫
```
```
2. JspView 클래스를 구현하기
- DispatcherServlet 에서 view에 해당하는 로직 이동
- 2단계에서 기존의 AnnotationHandlerMapping와 통합할 때 modelAndView 를 사용해서 JspView 로직을 완성할 것으로 예상
```
특히 저는 1번에서 뭘 어떻게 구현할지 몰라서 많이 헤매어서.... 구현에 정말 오랜 시간이 걸렸습니다🙀
제가 이번 미션을 제대로 해석한건지 호기의 의견을 듣고 싶습니다.
개인적으로 이번 구현에서 아쉬움이 많이 남는 부분입니다.
예외 처리를 우아하게 하고 싶었는데, 예외를 어디에서 잡고 던질지 계속 고민하다가 구현을 못하겠더라고요.
그래서 도움을 요청하고 일단 제출하는게 좋을 것 같아서 이렇게 의견을 여쭙습니다🆘
예를 들어서 아래와 같은 코드에서 발생할 수 있는 예외는 InstantiationException, …
=> [MVC 구현하기 - 1단계] 산초(나영서) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationExecutions.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScanner.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/Handler.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/Packages.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationExecutionsTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScannerTest.java
안녕하세요 제제! 🍊
2단계 구현해보았습니다!
기존에 AnnotationHandlerMapping 가 가지고 있던 복잡한 로직을 객체 분리와 함께 최대한 나눠보았습니다!
아직 리팩터링할 부분이 좀 보이는데 RC 반영해보면서 리팩터링 해보겠습니다!
제제도 많이 바쁠텐데 같이 화이팅입니다!😂
ps. 1단계 때 저의 생각을 물어보는 질문이 너무 좋았습니다! 이번에도 메타인지 알 수 있게 질문해주시면 정말 도움이 많이 될 것 같아요!😊
=> [MVC 구현하기 - 2단계] 타칸(최원준) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/Handler.java, app/src/main/java/com/techcourse/ManualHandler.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/test/java/com/techcourse/ManualHandlerMappingTest.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandler.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/Handler.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMapping.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestController.java
안녕하세요 폭포!
이번엔 2단계로 찾아왔습니다!
데모 데이로 바쁘실 것 같은데 시간 나실 때 리뷰 부탁드릴께요~!
=> [MVC 구현하기 - 2단계] 호기(조호연) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/CompositeHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMapping.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/CompositeHandlerMappingTest.java
안녕하세요 뽀로로 ~
2단계 미션 요구사항데로 인터페이스 기반 컨트롤러와 어노테이션 기반 컨트롤러가 공존하도록 만들어 봤습니다.
저번 리뷰로도 많은 점을 배울 수 있었어요 
이번 리뷰도 잘 부탁드립니다
=> [MVC 구현하기 - 2단계] 카키(서현준) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/HandlerMappingRegistry.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScanner.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/InstanceInitializer.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ScanType.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScannerTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/InstanceInitializerTest.java, mvc/src/test/java/samples/NoConstructorController.java, mvc/src/test/java/samples/SubTypeController.java, mvc/src/test/java/samples/TestController.java, mvc/src/test/java/samples/TestServiceA.java, mvc/src/test/java/samples/TestServiceB.java
안녕하세요 카키 :>
데모데이 준비하느라 많이 바쁘셨을 것 같습니다
DispatcherServlet에서 이루어지는 기능들에 대한 기존 코드의 의도를 파악하기 어려웠습니다.
우선 제가 이해한 대로 기존 코드의 기능을 수행하도록 만들었습니다!
리뷰 잘부탁드리겠습니동 미리 감사합니다 :>:>
=> [MVC 구현하기 - 2단계] 도비(김도엽) 미션 제출합니다.

README.md, app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, app/src/test/java/com/techcourse/DispatcherServletTest.java, mvc/src/main/java/com/interface21/web/servlet/HandlerAdapter.java, mvc/src/main/java/com/interface21/web/servlet/HandlerAdaptor.java, mvc/src/main/java/com/interface21/web/servlet/HandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerHandlerAdaptor.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdaptorRegistry.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionAdaptor.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/utils/InstanceManager.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerHandlerAdaptorTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdaptorRegistryTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionAdaptorTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistryTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/utils/InstanceManagerTest.java, mvc/src/test/java/samples/TestController.java
안녕하세요 무빈~~ 
호다닥 2단계 PR로 찾아뵙습니다!
이번 미션 status는 다음과 같아요!
---
- InstanceManager 싱글턴 구조 변경
Map 필드를 추가했어용. :3 
- 요구사항 만족
- 테스트를 아직... 많이 못 짰습니다... ㅇ.ㅜ 
피드백 반영하면서 테스트도 추가해서 PR 쏘도록 할게요!
- ControllerScanning 관련 리팩토링을 하지 않았어요.
전에 말씀드린 것처럼 `AnnotationHandlerMapping`에서 컨트롤러 인스턴스 생성의 책임까지를 맡는 게 맞는지 고민이 되었어요. 🤔
`InstanceManager`에 컨트롤러들을 관리하는 `Map<Class<?>, Object` 필드도 생긴 이상 
더더욱 `HandlerExecution`에서 `handle` 메서드가 실행될 때 동적으로 `instance`를 받아와도 좋지 않을까 싶었거든요.
무빈은 이 부분에 대해 어떻게 생각하시나요?
- 메서드를 못 찾아올 때 `null` 반환 / `Optional.ofNullable()` 반환
기존 시그니처는 `null` 값으로 핸들러 유무를 판단하는 것 같았는데,
임의로 `Optional`을 활용했습니다. 
`NPE`를 발생시킬 수 있는 `null` 값을 활용하는 것보다는 조금 더 유연한 대처가 가능한 `Optional`을 활용하는 게 나을 것 같다는 판단에서였는데, 무빈은 어떻게 생각하세요? 
미리 말씀 드렸던 것보다 조금 많이 늦었죠... ㅇ. ㅠ 그래서 부랴부랴 우선 제출해봐요.
이번 리뷰도 잘 부탁드립니다~~~  (주말 잘 보내세요~~)
=> [2단계] 애쉬 미션 제출합니다

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/ControllerHandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScanner.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappings.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/asis/ControllerHandlerAdapterTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScanTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingsTest.java, mvc/src/test/java/samples/NotController.java, mvc/src/test/java/samples/OldController.java
안녕하세요, 페드로!
하루하루 어떻게 지나가는지 모르겠네요 ㅎㅎ 페드로는 잘 지내시나요?
이번 미션도 잘 부탁드립니다!
=> [MVC 구현하기 - 2단계] 우주(김성현) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutor.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegister.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutorTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegisterTest.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 도라~
조금 늦게 리뷰를 요청하게 되어 죄송합니다...
데모데이를 준비하며 프로젝트에 좀 더 집중했었습니다.. 😭
1단계도 좋은 리뷰 많이 남겨주셔서 도움이 많이 됐는데, 2단계에서도 잘 부탁드려요!!
=> [MVC 구현하기 - 2단계] 뽀로로(조경찬) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/test/java/com/techcourse/DispatcherServletTest.java, app/src/test/java/samples/TestAnnotationMvcController.java, app/src/test/java/samples/TestLegacyMvcController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/test/java/servlet/com/example/ServletTest.java
안녕하세요 마크! 
기존 제공된 뼈대 코드에서 app 패키지 내에 DispatcherServlet, TomcatStarter 등이 구현되어 있고 mvc 패키지에 정의한 모듈들을 가져다 쓰는 형식이라 주로 DispatcherServlet 위주로 변경되었습니다 :) 
추가로, 저번 단계에서 AnnotationHandlerMapping에서 그저 Exception을 던져주었는데 이번 단계에서 따로 예외 처리를 추가했습니다. 
기존에 발생하는 checked 예외들로도 예외 원인을 파악하기 쉽다고 생각했는데 DispatcherServlet에서 쓰려고 보니 ServletException으로 감싸는 건 어색하더라고요 😅 예외의 역할을 나누고 원인을 파악하기 쉽도록 예외 처리를 추가했습니다.
2단계도 잘 부탁드립니다. 🙇🏻‍♀️
=> [MVC 구현하기 - 2단계] 미아(이종미) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/LogoutController.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, app/src/main/java/com/techcourse/repository/InMemoryUserRepository.java, app/src/test/java/com/techcourse/DispatcherServletTest.java, app/src/test/java/com/techcourse/controller/RegisterControllerTest.java, app/src/test/java/com/techcourse/controller/RegisterViewControllerTest.java, docs/README.md, mvc/src/main/java/com/interface21/webmvc/servlet/HandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/HandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/View.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/Controller.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerHandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScanner.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapterRegistry.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionHandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerHandlerAdapterTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionHandlerAdapterTest.java
안녕하세요 폴라..!  오랜만입니다:) 
리뷰 요청이 늦어졌네요...ㅎ
이전 단계에서 제가 구현한 코드들의 의도를 물어봐주어 재밌었습니다 ㅎ.ㅎ
이번에도 잘부탁드립니다ㅏ
=> [MVC 구현하기 - 2단계] 레디(최동근) 미션 제출합니다:)

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScanner.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScannerTest.java
안녕하세요 재즈, 폰드입니다.🙇‍♂️
리팩터링 관련해서 리뷰 요청 드려요!
전에 남기신 코멘트도 반영했는데, 확인 부탁드립니다.
테스트 코드는 추가하도록 하겠습니다!
=> [MVC 구현하기 - 2단계] 폰드(권규택) 미션 제출합니다.

app/build.gradle, app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/ManualHandlerAdapter.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/LogoutController.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, app/src/test/java/com/techcourse/HandlerAdaptersTest.java, app/src/test/java/com/techcourse/HandlerMappingsTest.java, mvc/src/main/java/com/interface21/webmvc/servlet/ModelAndView.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/controller/Controller.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/controller/ForwardController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/AnnotationHandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/adapter/HandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/adapter/HandlerAdapters.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/mapping/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/mapping/HandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/handler/mapping/HandlerMappings.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/handler/AnnotationHandlerAdapterTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/handler/adapter/HandlerAdaptersTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/handler/mapping/HandlerMappingsTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java
안녕하세요 제우스!!
데모데이는 잘 마무리 하셨을까요??
이번 리뷰도 잘 부탁드리겠습니다!
코드 보시며 편하게 의견 주셔요 ㅎㅎ
=> [2단계 - MVC 구현하기] 낙낙(이낙헌) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/LoginRelacyController.java, app/src/main/java/com/techcourse/controller/LogoutRegacyController.java, app/src/main/java/com/techcourse/controller/RootController.java, app/src/main/java/com/techcourse/controller/UserController.java, app/src/main/java/com/techcourse/dispatcherServlet/DispatcherServletInitializer.java, app/src/main/java/com/techcourse/dispatcherServlet/handlerAdapter/ManualHandlerAdapter.java, app/src/main/java/com/techcourse/dispatcherServlet/handlerMapping/ManualHandlerMapping.java, app/src/main/java/com/techcourse/domain/User.java, app/src/main/webapp/index.html, app/src/main/webapp/index.jsp, app/src/main/webapp/register.jsp, app/src/test/java/com/techcourse/dispatcherServlet/handlerAdapter/ManualHandlerAdapterTest.java, mvc/src/main/java/com/interface21/webmvc/servlet/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/handlerAdapter/AnnotationHandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/handlerAdapter/HandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/handlerMapping/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/handlerMapping/HandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JsonView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerAdapterTest.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/src/test/java/di/stage3/context/DIContainer.java, study/src/test/java/di/stage4/annotations/ClassPathScanner.java, study/src/test/java/di/stage4/annotations/DIContainer.java, study/src/test/java/di/stage4/annotations/Stage4Test.java
커비 마지막 3단계도 잘부탁드립니다~~ 코드도 코드지만, 나오는 개념들 제대로 이해하고있는 지에 대한 질문도 주시면 감사합니다~!
=> [MVC 구현하기 - 3단계] 도도(김도선) 미션 제출합니다.

app/build.gradle, app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/build.gradle, mvc/src/main/java/com/interface21/webmvc/servlet/ModelAndView.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/build.gradle, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 드라고! 😊
학습 테스트를 모두 진행하고, 1단계 미션 완료에만 집중하여 구현하였습니다!
주석으로 해당 메서드의 동작을 달아두어서 제가 나중에 볼 때 이해하기 쉽도록 했습니다. 
드라고도 미션 천천히 하시고, 리뷰해주세요!!
리뷰 감사드려요!!
=> [1단계 - @MVC 프레임워크 구현하기] 모루(최동준) 미션 제출합니다.

app/build.gradle, mvc/build.gradle, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, study/build.gradle, study/src/main/java/servlet/com/example/BasicServlet.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/FormHandlingServlet.java, study/src/main/java/servlet/com/example/HttpMethodServlet.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 머피~
이번 MVC 미션의 리뷰어로 만나게 되어 영광입니다!
Reflection과 문자열 기반 파싱이 많아서 주로 가독성과 안전성을 중심으로 고민했습니다.
상세한 내용은 코드 내 코멘트로 남겨두겠습니다.
[변경 커밋 내역](https://github.com/woowacourse/java-mvc/pull/886/files/2dac559e9c492d1a267e40f71508fd43fa3b9d92..66a45ee186042c9c21b136d7732f68e3f3bd9d85)에는 학습 테스트 커밋이 제외되어 있습니다!
잘 부탁드려요! 😄 
1단계 요구사항에 따라, 어노테이션 기반의 새로운 MVC 프레임워크의 핵심 기능을 구현합니다.
기존의 수동 URL 매핑 방식의 불편함을 개선하고, 어노테이션을 통해 컨트롤러와 메서드를 자동으로 탐색하고 매핑하는 기능을 제공하는 것을 목표로 합니다.
- `AnnotationHandlerMapping#initialize` 구현
- JSP 클래스 구현
=> [1단계 - @MVC 프레임워크 구현하기] 벨로(방예혁) 미션 제출합니다.

app/build.gradle, app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ViewResolver.java, mvc/build.gradle, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, study/build.gradle, study/src/main/java/servlet/com/example/BasicServlet.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/FormHandlingServlet.java, study/src/main/java/servlet/com/example/HttpMethodServlet.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 서프! 이번 mvc 미션 동안 잘 부탁드립니다~
이번 미션에서는 학습 테스트를 공부하고 미션을 진행하면서 전체적인 로직을 이해하는데 집중해보았습니다!
학습 테스트 커밋을 제외한 커밋 범위 링크입니다! : [커밋 범위 링크](https://github.com/woowacourse/java-mvc/pull/897/files/d405c5ebae3bfffc89f61aec0ac4d4b541e572a7..b4fc1417d930d980c6611b5048435d5381f00113)
- AnnotationHandlerMapping 구현
- DispatcherServlet 내 View 로직 JspView로 분리
=> [1단계 - @MVC 프레임워크 구현하기] 플린트(이주환) 미션 제출합니다.

app/build.gradle, app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/build.gradle, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerKey.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/build.gradle, study/src/main/java/servlet/com/example/BasicServlet.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/FormHandlingServlet.java, study/src/main/java/servlet/com/example/HttpMethodServlet.java, study/src/main/java/servlet/com/example/KoreanServlet.java, study/src/main/java/servlet/com/example/SharedCounterServlet.java, study/src/test/java/reflection/Junit3Test.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4Test.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 새로이 😄
이번 미션에서 리뷰어로 새로이를 만나게 되어 정말 감격스럽습니다 😭
이번 스텝에서는 초기 패키지 구조가 방대하게 느껴져 아직 책임 분리가 완전히 이루어지지는 않은 상태입니다.
지금은 하나씩 어떤 책임을 어디에 두어야 할지 학습하며, 요구사항을 만족시키기 위한 최소 로직만 구현한 상태입니다.
테코톡 주간이라 바쁘시겠지만, 리뷰 잘 부탁드립니다! (코멘트 적어도 서운해만 할게요 괜찮아요)
=> [1단계 - @MVC 프레임워크 구현하기] 에드(김진우) 미션 제출합니다.

app/build.gradle, mvc/build.gradle, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, study/build.gradle, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 리버 😄
이번 미션에서는 `AnnotationHandlerMapping`과 `JspView`를 구현해봤어요.
1단계 미션에 대한 변경사항은 [해당 링크](https://github.com/woowacourse/java-mvc/pull/890/files/fc7f5dd006252c11f3030892bf082768424001b8..0231b7fd0ef583c0d96355fb36bfc26dcd0f2c06)에서 확인하실 수 있어요.
미션을 진행하고 천천히 리뷰해주셔도 됩니다!
피드백은 자유롭게 남겨주세요!
이번 리뷰 잘 부탁드립니다 🙇‍♀️🙇‍♀️
=> [1단계 - @MVC 프레임워크 구현하기] 루키(김준하) 미션 제출합니다.

app/build.gradle, app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/build.gradle, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/build.gradle, study/src/main/java/servlet/com/example/BasicServlet.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/FormHandlingServlet.java, study/src/main/java/servlet/com/example/HttpMethodServlet.java, study/src/main/java/servlet/com/example/KoreanServlet.java, study/src/main/java/servlet/com/example/LocalCounterServlet.java, study/src/main/java/servlet/com/example/ServletApplication.java, study/src/main/java/servlet/com/example/SharedCounterServlet.java, study/src/main/java/servlet/com/example/TomcatStarter.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 모루 🙋 만나서 반갑습니다. 잘 부탁 드립니다!
[Step1 커밋 목록](https://github.com/woowacourse/java-mvc/pull/898/files/c1b6e702e2eab3fd407705b25e19f8cde36ac42f..6c16251be848f75f0bd294665ab8acf589e833ed#diff-c6443fd91aa32fc45e79bab352a22917a3f2325fd987e100d713c71abee129b4) 
1. MVC Framework 테스트 통과하기
`basePackages` 경로 내 `@Controller` 어노테이션이 붙은 클래스에 한하여, 
`@RequestMapping` 어노테이션에서 uri 및 method를 추출 해 handlerExecutions 에 등록합니다.
2. JspView 클래스를 구현.
`DispatcherServlet` 의 service 메서드 뷰에 처리 분리 후 `JspView` 로 이동합니다.
=> [1단계 - @MVC 프레임워크 구현하기] 제프리(홍성호) 미션 제출합니다.

app/build.gradle, app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/build.gradle, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, study/build.gradle, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세용 체체~
이번 미션에서 리플렉션 API를 공부하고, 1단계를 구현해봤는데요. 아 이거 상당히 복잡하더라구요.
그래도 어찌저찌 미션을 완수했습니다!
DispatcherServlet에서 현재는 `ManualHandlerMapping`를 사용 중인데, 이는 2단계 요구사항이라서 변경하지 않았어요!~
---
- `AnnotationHandlerMapping` 클래스 구현
- `Controller` 어노테이션이 붙은 클래스와 `@RequestMapping` 어노테이션이 붙은 메소드를 `HandlerExecution`으로 매핑합니다.
- `@RequestMapping` 어노테이션 메서드 중 method가 지정되지 않았다면, 모든 method에 매핑됩니다.
- 또한, method 다중 매핑을 지원합니다.
- `DispatcherServlet`이 갖고 있던 뷰 렌더링 책임을 `JspView`로 이동
=> [1단계 - @MVC 프레임워크 구현하기] 율무(강기석) 미션 제출합니다.

app/build.gradle, mvc/build.gradle, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, study/build.gradle
안녕하세요 젠슨~ 😊
이번 요구 사항 구현 정리입니다.
1. MVC Framework 테스트 통과하기
basePackages 경로 내 @Controller 어노테이션이 붙은 클래스에 한하여,
@RequestMapping 어노테이션에서 uri 및 method를 추출 해 handlerExecutions 에 등록합니다.
2. HandlerExecution 클래스 구현하기
실행할 메서드를 가지고 해당 메서드를 실행시킵니다. 현재는 ModelAndView만 반환한다고 가정해서 확장성 생각 안하고 바로 반환하였습니다. Step2에서 실행할 메서드에 리턴 타입(ModelAndView, JSON 등)에 따라 ModelAndView를 반환하도록 리팩토링 할 예정입니다.
3. JspView 클래스를 구현하기
DispatcherServlet 의 service 메서드 뷰에 처리 분리 후 JspView 로 이동합니다..
=> [1단계 - @MVC 프레임워크 구현하기] 코기(장재현) 미션 제출합니다.

app/build.gradle, app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/README.md, mvc/build.gradle, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/build.gradle, study/src/main/java/servlet/com/example/BasicServlet.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/FormHandlingServlet.java, study/src/main/java/servlet/com/example/HttpMethodServlet.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요, 율무~ 반가워요 👐🏻
이번 단계에 대한 코드는 다음 링크에서 보면 편하게 볼 수 있습니다!
[1단계 변경 사항](https://github.com/woowacourse/java-mvc/pull/888/files/138839f015d853dd5627bca4a83f86710e80262c..e748d36022e6d87af0f0fba7b0dc0ff7a4a3fa8a)
1단계다 보니 미션 요구사항인 `AnnotaionHandlerMappingTest`를 통과하는데 초점을 맞추어 진행했습니다.
=> [1단계 - @MVC 프레임워크 구현하기] 사나(조은산) 미션 제출합니다.

app/build.gradle, mvc/build.gradle, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/samples/TestController.java, study/build.gradle, study/src/main/java/servlet/com/example/BasicServlet.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/FormHandlingServlet.java, study/src/main/java/servlet/com/example/HttpMethodServlet.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/ReflectionTest.java
반가워요 미소^^
요구사항에 맞춰서 처리했어서 좀 더 학습하면 좋은 거 있으면 알려주시면 감사하겠습니다~
=> [1단계 - @MVC 프레임워크 구현하기] 꾹이(이기욱) 미션 제출합니다.

app/build.gradle, app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/build.gradle, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, study/build.gradle
하루 안녕하세요.  ☺️
만나서 반갑습니다. 
앞으로 `@MVC` 구현하기 미션 리뷰 잘 부탁드립니다. 😊
하루가 미션을 완료한 뒤 천천히 해주셔도 됩니다. 📣
이번 미션에서는 학습 테스트를 공부하고 미션을 진행하며 전체적인 로직을 이해하는데 집중했습니다.  
특히 평소에 접하던 메서드들이 아니라 최대한 메서드명을 통해 동작을 이해하기 쉽도록 분리해보았습니다.  
또한 필요하다고 생각되는 부분에는 주석을 넣어놓았습니다. 
1. `AnnotationHandlerMapping` 구현
2. JspView 클래스를 구현하고 `DispatcherServlet.service` 메서드에 적용
=> [1단계 - @MVC 프레임워크 구현하기] 새로이(강철원) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/build.gradle, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, study/build.gradle, study/src/main/java/servlet/com/example/BasicServlet.java, study/src/main/java/servlet/com/example/FormHandlingServlet.java, study/src/main/java/servlet/com/example/HttpMethodServlet.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요! 한스
2번째 요구사항을 구현했는데
이게 맞는건지 혼란이 있긴합니다. 
리뷰 잘 부탁드립니다
=> [1단계 - @MVC 프레임워크 구현하기] 드라고(이용화) 미션 제출합니다.

app/build.gradle, app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/LogoutController.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, mvc/build.gradle, mvc/src/main/java/com/interface21/webmvc/servlet/ModelAndView.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/Controller.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/ForwardController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, mvc/src/test/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMappingTest.java, mvc/src/test/java/samples/TestController.java, study/build.gradle, study/src/main/java/servlet/com/example/BasicServlet.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/FormHandlingServlet.java, study/src/main/java/servlet/com/example/HttpMethodServlet.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java
안녕하세요 밍트, 1단계 제출합니다!
학습 테스트로 인해 변경 파일이 많아, 미션에 해당 되는 변경 범위 링크를 함께 첨부할게요.
https://github.com/woowacourse/java-mvc/pull/881/files/d054806ac27272a44bd26c7aafb75b924ccd1b65..35293b8c2223b6a34b6e6a0738407132f73b7592
시간 되실 때 편하게 리뷰해주시면 감사하겠습니다~~
=> [1단계 - @MVC 프레임워크 구현하기] 젠슨(이성우) 미션 제출합니다. 

app/build.gradle, app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/controller/LoginController.java, app/src/main/java/com/techcourse/controller/LoginViewController.java, app/src/main/java/com/techcourse/controller/LogoutController.java, app/src/main/java/com/techcourse/controller/RegisterController.java, app/src/main/java/com/techcourse/controller/RegisterViewController.java, mvc/build.gradle, mvc/src/main/java/com/interface21/web/bind/annotation/RequestMethod.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/Controller.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/ForwardController.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, study/build.gradle, study/src/main/java/servlet/com/example/BasicServlet.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/FormHandlingServlet.java, study/src/main/java/servlet/com/example/HttpMethodServlet.java, study/src/main/java/servlet/com/example/SharedCounterServlet.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요 우가!
이번 미션 리뷰어로 만나서 반갑습니다 ㅎㅎ
잘 부탁드립니다~!
=> [1단계 - @MVC 프레임워크 구현하기] 포포(이민우) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, docs/Project_Structure_step1.md, mvc/build.gradle, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, study/build.gradle, study/src/main/java/servlet/com/example/BasicServlet.java, study/src/main/java/servlet/com/example/CharacterEncodingFilter.java, study/src/main/java/servlet/com/example/FromHandlingServlet.java, study/src/main/java/servlet/com/example/HttpMethodServlet.java, study/src/main/java/servlet/com/example/LocalCounterServlet.java, study/src/main/java/servlet/com/example/SharedCounterServlet.java, study/src/test/java/reflection/Junit3TestRunner.java, study/src/test/java/reflection/Junit4TestRunner.java, study/src/test/java/reflection/ReflectionTest.java, study/src/test/java/reflection/ReflectionsTest.java
안녕하세요! 코기!
리뷰이로 만나뵙게 되어 반갑습니다! 
리뷰 요청을 먼저 드리기는 했지만, 시간 여유가 있으실 때 편하게 봐주셔도 좋을 것 같아요!
이번 미션동안 리뷰 잘부탁드립니다!
=> [1단계 - @MVC 프레임워크 구현하기] 랜디(김정우) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, app/src/main/java/com/techcourse/ManualHandlerMapping.java, app/src/main/java/com/techcourse/controller/RegisterController.java, mvc/src/main/java/com/interface21/core/util/ReflectionUtils.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/HandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/HandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/ControllerHandlerAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/ControllerScanner.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecutionAdapter.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerMappingRegistry.java
안녕하세요 제프~
제프가 심심해보여서 얼른 step2도 가져왔습니다 ☺️
지난 pr에 리뷰해준 것들은 확인하고 반영해보았어요
이번 리뷰도 제프가 중요하게 생각하는 부분에 대해 자유롭게 해주세요!
- Manual HandlerMapping와 Annotation HandlerMapping 공존
- 리플렉션 기반 컨트롤러 탐색 역할 ControllerScanner로 분리
- HandlerMapping, HandlerAdapter 추상화
=> [2단계 - 점진적인 리팩터링] 엠제이(최민준) 미션 제출합니다.

app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/asis/Controller.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java
안녕하세요 포라 ! 이번 미션에 만나서 영광입니다 👍 
포라가 미션을 수행한 뒤 리뷰해주셔도 됩니다! 
파이팅!
=> [1단계 - @MVC 프레임워크 구현하기] 체체(김진영) 미션 제출합니다. 

app/build.gradle, app/src/main/java/com/techcourse/DispatcherServlet.java, mvc/build.gradle, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/AnnotationHandlerMapping.java, mvc/src/main/java/com/interface21/webmvc/servlet/mvc/tobe/HandlerExecution.java, mvc/src/main/java/com/interface21/webmvc/servlet/view/JspView.java, study/build.gradle
안녕하세요 멍구! 오랜만에 리뷰어로 만나게 되어서 반가워요 🤗
이번 단계에서는 요구사항을 충족하는데만 집중했습니다. 다만, 리플렉션을 제대로 사용해본 것은 처음이라 구현을 잘 했는지 걱정이네요 ㅎ
이번 미션 잘 부탁드립니다~
=> [1단계 - @MVC 프레임워크 구현하기] 짱구(박준혁) 미션 제출합니다.
